# shellcheck shell=bash
# Traefik route generation for public TLS modes.

# Emit bot-block router YAML if FM_EDGE_BLOCK_BOT_PROBES=true. Caller passes
# an optional host prefix (empty for selfsigned, `Host(`domain`)` for LE) and
# the tls block. The regex pattern comes from FM_EDGE_BLOCK_BOT_PROBES_PATTERNS
# (single source of truth). YAML uses single-quoted scalar so regex backslashes
# pass through verbatim. Empty output when disabled or no patterns set.
_bot_block_router_yaml() {
    local host_prefix="$1"
    local tls_block="$2"
    local enabled="${FM_EDGE_BLOCK_BOT_PROBES:-false}"
    local patterns="${FM_EDGE_BLOCK_BOT_PROBES_PATTERNS:-}"
    if [ "$enabled" != "true" ] || [ -z "$patterns" ]; then
        return 0
    fi
    local rule="PathRegexp(\`${patterns}\`)"
    if [ -n "$host_prefix" ]; then
        rule="${host_prefix} && ${rule}"
    fi
    cat <<YAML
    # Edge bot-probe block (FM_EDGE_BLOCK_BOT_PROBES). Routes known scanner
    # paths to a sink service with no backends so Traefik returns 503 before
    # the request reaches FM. Toggle off in deploy/env/*.env for testing.
    bot-block:
      rule: '${rule}'
      entryPoints: [web, websecure]
      service: bot-block-sink
      priority: 250
${tls_block}
YAML
}

_bot_block_sink_service_yaml() {
    local enabled="${FM_EDGE_BLOCK_BOT_PROBES:-false}"
    if [ "$enabled" != "true" ]; then
        return 0
    fi
    cat <<'YAML'
    bot-block-sink:
      loadBalancer:
        servers: []
YAML
}

write_traefik_routes_selfsigned() {
    local dyn_dir="$STATE_DIR/tls/dynamic"
    mkdir -p "$dyn_dir"

    local plain_ws="${FM_PLAIN_WS:-false}"
    local plain_ws_block=""
    if [ "$plain_ws" = "true" ]; then
        plain_ws_block='    # Plain ws:// on port 80 for /shelly — Wall Display devices whose
    # firmware only trusts Allterco CA and cannot validate non-Allterco TLS.
    shelly-ws:
      rule: "PathPrefix(`/shelly`)"
      entryPoints: [web]
      service: fleet
      priority: 200'
    fi
    local bot_block_router
    bot_block_router=$(_bot_block_router_yaml "" "      tls: {}")
    local bot_block_service
    bot_block_service=$(_bot_block_sink_service_yaml)

    local rl_avg="${FM_LOGIN_RATE_LIMIT_AVERAGE:-10}"
    local rl_burst="${FM_LOGIN_RATE_LIMIT_BURST:-30}"
    local rl_period="${FM_LOGIN_RATE_LIMIT_PERIOD:-1m}"
    cat > "$dyn_dir/routes.yml" <<EOF
# Auto-generated by deploy-public.sh — static routes for file provider
http:
  routers:
${plain_ws_block}
${bot_block_router}
    # Redirect all other HTTP traffic to HTTPS
    http-catchall:
      rule: "PathPrefix(\`/\`)"
      entryPoints: [web]
      service: fleet
      priority: 1
      middlewares: [redirect-https]
    # HTTPS routers
    zitadel-oauth:
      rule: "PathPrefix(\`/oauth/\`)"
      entryPoints: [websecure]
      service: zitadel-api
      tls: {}
      priority: 120
      middlewares: [login-rate-limit, strip-feature-policy]
    # Login V2 static assets — bypass rate-limit (Next.js parallel chunk loads).
    zitadel-login-assets:
      rule: "PathPrefix(\`/ui/v2/login/_next\`) || PathPrefix(\`/ui/v2/login/static\`) || PathPrefix(\`/ui/v2/login/icon-\`) || PathPrefix(\`/ui/v2/login/favicon\`)"
      entryPoints: [websecure]
      service: zitadel-login
      tls: {}
      priority: 115
      middlewares: [strip-feature-policy]
    zitadel-login:
      rule: "PathPrefix(\`/ui/v2/login\`)"
      entryPoints: [websecure]
      service: zitadel-login
      tls: {}
      priority: 110
      middlewares: [login-rate-limit, strip-feature-policy]
    zitadel-api:
      rule: "PathPrefix(\`/.well-known/\`) || PathPrefix(\`/oidc/\`) || PathPrefix(\`/ui/\`) || PathPrefix(\`/debug/\`) || PathPrefix(\`/v2beta/\`) || PathPrefix(\`/v2/\`) || PathPrefix(\`/management/\`) || PathPrefix(\`/admin/\`) || PathPrefix(\`/auth/v1/\`) || PathPrefix(\`/assets/v1/\`) || PathPrefix(\`/zitadel.\`)"
      entryPoints: [websecure]
      service: zitadel-api
      tls: {}
      priority: 100
      middlewares: [strip-feature-policy]
    fleet:
      rule: "PathPrefix(\`/\`)"
      entryPoints: [websecure]
      service: fleet
      tls: {}
      priority: 10
      middlewares: [gzip-compress, strip-identity, strip-feature-policy]
  services:
    fleet:
      loadBalancer:
        servers:
          - url: "http://fleet-manager:7011"
    zitadel-login:
      loadBalancer:
        servers:
          - url: "http://zitadel-login:3000"
    zitadel-api:
      loadBalancer:
        servers:
          - url: "h2c://zitadel-api:8080"
${bot_block_service}
  middlewares:
    gzip-compress:
      compress:
        excludedContentTypes:
          - application/octet-stream
    strip-identity:
      headers:
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
    strip-feature-policy:
      headers:
        customResponseHeaders:
          Feature-Policy: ""
          Permissions-Policy: ""
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    login-rate-limit:
      rateLimit:
        average: ${rl_avg}
        burst: ${rl_burst}
        period: ${rl_period}
        sourceCriterion:
          ipStrategy:
            depth: 1
EOF

    chmod 0644 "$dyn_dir/routes.yml"
    ok "Traefik routing config written"
}

write_traefik_routes_letsencrypt() {
    local domain="$1"
    local dyn_dir="$STATE_DIR/traefik-dynamic"
    mkdir -p "$dyn_dir"
    mkdir -p "$STATE_DIR/letsencrypt"

    local plain_ws="${FM_PLAIN_WS:-false}"
    local plain_ws_block=""
    if [ "$plain_ws" = "true" ]; then
        plain_ws_block="    # Plain ws:// on port 80 for /shelly — Wall Display devices whose
    # firmware only trusts Allterco CA and cannot validate Let's Encrypt certs.
    shelly-ws:
      rule: \"Host(\`${domain}\`) && PathPrefix(\`/shelly\`)\"
      entryPoints: [web]
      service: fleet
      priority: 200"
    fi

    local bot_block_router
    bot_block_router=$(_bot_block_router_yaml \
        "Host(\`${domain}\`)" \
        "      tls:
        certResolver: letsencrypt")
    local bot_block_service
    bot_block_service=$(_bot_block_sink_service_yaml)

    local rl_avg_le="${FM_LOGIN_RATE_LIMIT_AVERAGE:-10}"
    local rl_burst_le="${FM_LOGIN_RATE_LIMIT_BURST:-30}"
    local rl_period_le="${FM_LOGIN_RATE_LIMIT_PERIOD:-1m}"
    cat > "$dyn_dir/routes.yml" <<EOF
# Auto-generated by deploy-public.sh — static routes for file provider
http:
  routers:
${plain_ws_block}
${bot_block_router}
    # Redirect all other HTTP traffic to HTTPS
    http-catchall:
      rule: "Host(\`${domain}\`)"
      entryPoints: [web]
      service: fleet
      priority: 1
      middlewares: [redirect-https]
    # HTTPS routers
    zitadel-oauth:
      rule: "Host(\`${domain}\`) && PathPrefix(\`/oauth/\`)"
      entryPoints: [websecure]
      service: zitadel-api
      tls:
        certResolver: letsencrypt
      priority: 120
      middlewares: [login-rate-limit, strip-feature-policy]
    # Login V2 static assets — bypass rate-limit (Next.js parallel chunk loads).
    zitadel-login-assets:
      rule: "Host(\`${domain}\`) && (PathPrefix(\`/ui/v2/login/_next\`) || PathPrefix(\`/ui/v2/login/static\`) || PathPrefix(\`/ui/v2/login/icon-\`) || PathPrefix(\`/ui/v2/login/favicon\`))"
      entryPoints: [websecure]
      service: zitadel-login
      tls:
        certResolver: letsencrypt
      priority: 115
      middlewares: [strip-feature-policy]
    zitadel-login:
      rule: "Host(\`${domain}\`) && PathPrefix(\`/ui/v2/login\`)"
      entryPoints: [websecure]
      service: zitadel-login
      tls:
        certResolver: letsencrypt
      priority: 110
      middlewares: [login-rate-limit, strip-feature-policy]
    zitadel-api:
      rule: "Host(\`${domain}\`) && (PathPrefix(\`/.well-known/\`) || PathPrefix(\`/oidc/\`) || PathPrefix(\`/ui/\`) || PathPrefix(\`/debug/\`) || PathPrefix(\`/v2beta/\`) || PathPrefix(\`/v2/\`) || PathPrefix(\`/management/\`) || PathPrefix(\`/admin/\`) || PathPrefix(\`/auth/v1/\`) || PathPrefix(\`/assets/v1/\`) || PathPrefix(\`/zitadel.\`))"
      entryPoints: [websecure]
      service: zitadel-api
      tls:
        certResolver: letsencrypt
      priority: 100
      middlewares: [strip-feature-policy]
    fleet:
      rule: "Host(\`${domain}\`)"
      entryPoints: [websecure]
      service: fleet
      tls:
        certResolver: letsencrypt
      priority: 10
      middlewares: [gzip-compress, strip-identity, strip-feature-policy]
  services:
    fleet:
      loadBalancer:
        servers:
          - url: "http://fleet-manager:7011"
    zitadel-login:
      loadBalancer:
        servers:
          - url: "http://zitadel-login:3000"
    zitadel-api:
      loadBalancer:
        servers:
          - url: "h2c://zitadel-api:8080"
${bot_block_service}
  middlewares:
    gzip-compress:
      compress:
        excludedContentTypes:
          - application/octet-stream
    strip-identity:
      headers:
        customResponseHeaders:
          Server: ""
          X-Powered-By: ""
    strip-feature-policy:
      headers:
        customResponseHeaders:
          Feature-Policy: ""
          Permissions-Policy: ""
    redirect-https:
      redirectScheme:
        scheme: https
        permanent: true
    login-rate-limit:
      rateLimit:
        average: ${rl_avg_le}
        burst: ${rl_burst_le}
        period: ${rl_period_le}
        sourceCriterion:
          ipStrategy:
            depth: 1
EOF

    chmod 0644 "$dyn_dir/routes.yml"
    ok "Traefik routing config written (Let's Encrypt)"
}
