#!/usr/bin/env bash
#
# Generate Zitadel Postgres init SQL with dynamic password
#
# The original init-zitadel-db.sql hardcodes 'zitadel' as the password,
# but compose uses ${ZITADEL_DB_USER_PASSWORD}. This script generates
# deploy/state/init-zitadel-db.sql with the correct password.
#
# Note: Postgres init SQL only runs on first startup (empty data volume).
# Existing deployments need `deploy.sh down --volumes` to reset if passwords change.
#
# Usage: init-zitadel-db.sh
# Env:   ZITADEL_DB_USER_PASSWORD (required)
# Output: deploy/state/init-zitadel-db.sql

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
STATE_DIR="$DEPLOY_DIR/state"

if [ -z "${ZITADEL_DB_USER_PASSWORD:-}" ]; then
    echo "ERROR: ZITADEL_DB_USER_PASSWORD is not set" >&2
    exit 1
fi

mkdir -p "$STATE_DIR"

# Escape single quotes in password for SQL safety
ESCAPED_PASSWORD="${ZITADEL_DB_USER_PASSWORD//\'/\'\'}"

cat > "$STATE_DIR/init-zitadel-db.sql" <<SQL
-- Auto-generated by init-zitadel-db.sh — do not edit
-- Create Zitadel user and grant permissions (IF NOT EXISTS avoids conflict
-- with Zitadel's own start-from-init which also creates this user)
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'zitadel') THEN
    CREATE USER zitadel WITH PASSWORD '${ESCAPED_PASSWORD}';
  ELSE
    ALTER USER zitadel WITH PASSWORD '${ESCAPED_PASSWORD}';
  END IF;
END
\$\$;
GRANT ALL PRIVILEGES ON DATABASE zitadel TO zitadel;

-- Grant schema creation rights (needed for Zitadel's initialization)
ALTER USER zitadel CREATEDB;
SQL

chmod 0644 "$STATE_DIR/init-zitadel-db.sql"
echo "Generated $STATE_DIR/init-zitadel-db.sql"
