#!/usr/bin/env bash
#
# Generate RSA keypair and config for Zitadel System API
#
# This enables the bootstrap script to add custom instance domains,
# allowing Docker-internal container-to-container communication.
#
# Idempotent: only generates if keypair doesn't already exist.
#
# Output:
#   deploy/state/system-api/system-user.pem      — RSA private key
#   deploy/state/system-api/system-user.pub       — RSA public key
#   deploy/state/system-api/system-api-config.yaml — Zitadel config override
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

SYSTEM_API_DIR="$DEPLOY_DIR/state/system-api"
PRIVATE_KEY="$SYSTEM_API_DIR/system-user.pem"
PUBLIC_KEY="$SYSTEM_API_DIR/system-user.pub"
CONFIG_FILE="$SYSTEM_API_DIR/system-api-config.yaml"
SYSTEM_USER_NAME="system-user-1"

mkdir -p "$SYSTEM_API_DIR"
# Zitadel container (UID 1000) needs to read config + public key from this dir
chmod 0755 "$SYSTEM_API_DIR"

# Generate keypair if not exists
if [ -f "$PRIVATE_KEY" ] && [ -f "$PUBLIC_KEY" ]; then
    echo "  System API keypair already exists"
else
    echo "  Generating RSA keypair for System API..."
    # --traditional flag ensures PKCS1 format (required by Zitadel)
    openssl genrsa -traditional -out "$PRIVATE_KEY" 2048 2>/dev/null
    openssl rsa -in "$PRIVATE_KEY" -outform PEM -pubout -out "$PUBLIC_KEY" 2>/dev/null
    chmod 0600 "$PRIVATE_KEY"
    echo "  Keypair generated"
fi

# Always regenerate config (in case paths change)
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by init-system-api.sh — do not edit manually
SystemAPIUsers:
  ${SYSTEM_USER_NAME}:
    Path: /system-api/system-user.pub
EOF

chmod 0644 "$CONFIG_FILE" "$PUBLIC_KEY"
echo "  Config written: $CONFIG_FILE"
