--------------UP
CREATE TABLE device.groups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(300) NOT NULL,
    devices TEXT[] DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    parent_id INTEGER DEFAULT NULL REFERENCES device.groups(id) ON DELETE SET NULL,
    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMPTZ DEFAULT NULL
);
CREATE INDEX idx_device_groups_parent_id ON device.groups(parent_id);
--------------DOWN
DROP TABLE IF EXISTS device.groups;
