/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/alerts': RouteRecordInfo<
      '/alerts',
      '/alerts',
      Record<never, never>,
      Record<never, never>,
      | '/alerts/'
      | '/alerts/channels/'
      | '/alerts/channels/[id]'
      | '/alerts/destinations/[id]'
      | '/alerts/rules/'
      | '/alerts/rules/[id]'
      | '/alerts/templates'
    >,
    '/alerts/': RouteRecordInfo<
      '/alerts/',
      '/alerts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/alerts/channels/': RouteRecordInfo<
      '/alerts/channels/',
      '/alerts/channels',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/alerts/channels/[id]': RouteRecordInfo<
      '/alerts/channels/[id]',
      '/alerts/channels/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/alerts/destinations/[id]': RouteRecordInfo<
      '/alerts/destinations/[id]',
      '/alerts/destinations/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/alerts/rules/': RouteRecordInfo<
      '/alerts/rules/',
      '/alerts/rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/alerts/rules/[id]': RouteRecordInfo<
      '/alerts/rules/[id]',
      '/alerts/rules/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/alerts/templates': RouteRecordInfo<
      '/alerts/templates',
      '/alerts/templates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/signinwin/zitadel': RouteRecordInfo<
      '/auth/signinwin/zitadel',
      '/auth/signinwin/zitadel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automations': RouteRecordInfo<
      '/automations',
      '/automations',
      Record<never, never>,
      Record<never, never>,
      | '/automations/'
      | '/automations/actions'
      | '/automations/grafana'
      | '/automations/node-red'
      | '/automations/variables'
    >,
    '/automations/': RouteRecordInfo<
      '/automations/',
      '/automations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automations/actions': RouteRecordInfo<
      '/automations/actions',
      '/automations/actions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automations/grafana': RouteRecordInfo<
      '/automations/grafana',
      '/automations/grafana',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automations/node-red': RouteRecordInfo<
      '/automations/node-red',
      '/automations/node-red',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automations/variables': RouteRecordInfo<
      '/automations/variables',
      '/automations/variables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/callback': RouteRecordInfo<
      '/callback',
      '/callback',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dash': RouteRecordInfo<
      '/dash',
      '/dash',
      Record<never, never>,
      Record<never, never>,
      | '/dash/'
      | '/dash/[id]'
      | '/dash/analytics/[id]'
      | '/dash/control/[id]'
      | '/dash/energy/[id]'
      | '/dash/environment/[id]'
      | '/dash/manage'
      | '/dash/map/[id]'
      | '/dash/overview/[id]'
      | '/dash/safety/[id]'
    >,
    '/dash/': RouteRecordInfo<
      '/dash/',
      '/dash',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dash/[id]': RouteRecordInfo<
      '/dash/[id]',
      '/dash/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/analytics/[id]': RouteRecordInfo<
      '/dash/analytics/[id]',
      '/dash/analytics/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/control/[id]': RouteRecordInfo<
      '/dash/control/[id]',
      '/dash/control/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/energy/[id]': RouteRecordInfo<
      '/dash/energy/[id]',
      '/dash/energy/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/environment/[id]': RouteRecordInfo<
      '/dash/environment/[id]',
      '/dash/environment/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/manage': RouteRecordInfo<
      '/dash/manage',
      '/dash/manage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dash/map/[id]': RouteRecordInfo<
      '/dash/map/[id]',
      '/dash/map/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/overview/[id]': RouteRecordInfo<
      '/dash/overview/[id]',
      '/dash/overview/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dash/safety/[id]': RouteRecordInfo<
      '/dash/safety/[id]',
      '/dash/safety/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/devices': RouteRecordInfo<
      '/devices',
      '/devices',
      Record<never, never>,
      Record<never, never>,
      | '/devices/'
      | '/devices/discovered'
    >,
    '/devices/': RouteRecordInfo<
      '/devices/',
      '/devices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/devices/discovered': RouteRecordInfo<
      '/devices/discovered',
      '/devices/discovered',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring': RouteRecordInfo<
      '/monitoring',
      '/monitoring',
      Record<never, never>,
      Record<never, never>,
      | '/monitoring/'
      | '/monitoring/activity'
      | '/monitoring/audit-log'
      | '/monitoring/commands'
      | '/monitoring/connections'
      | '/monitoring/control-panel'
      | '/monitoring/database'
      | '/monitoring/device-ingest'
      | '/monitoring/events'
      | '/monitoring/host'
      | '/monitoring/investigate'
      | '/monitoring/logs'
      | '/monitoring/overview'
      | '/monitoring/resources'
      | '/monitoring/runtime'
      | '/monitoring/services'
      | '/monitoring/troubleshoot'
    >,
    '/monitoring/': RouteRecordInfo<
      '/monitoring/',
      '/monitoring',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/activity': RouteRecordInfo<
      '/monitoring/activity',
      '/monitoring/activity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/audit-log': RouteRecordInfo<
      '/monitoring/audit-log',
      '/monitoring/audit-log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/commands': RouteRecordInfo<
      '/monitoring/commands',
      '/monitoring/commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/connections': RouteRecordInfo<
      '/monitoring/connections',
      '/monitoring/connections',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/control-panel': RouteRecordInfo<
      '/monitoring/control-panel',
      '/monitoring/control-panel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/database': RouteRecordInfo<
      '/monitoring/database',
      '/monitoring/database',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/device-ingest': RouteRecordInfo<
      '/monitoring/device-ingest',
      '/monitoring/device-ingest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/events': RouteRecordInfo<
      '/monitoring/events',
      '/monitoring/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/host': RouteRecordInfo<
      '/monitoring/host',
      '/monitoring/host',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/investigate': RouteRecordInfo<
      '/monitoring/investigate',
      '/monitoring/investigate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/logs': RouteRecordInfo<
      '/monitoring/logs',
      '/monitoring/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/overview': RouteRecordInfo<
      '/monitoring/overview',
      '/monitoring/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/resources': RouteRecordInfo<
      '/monitoring/resources',
      '/monitoring/resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/runtime': RouteRecordInfo<
      '/monitoring/runtime',
      '/monitoring/runtime',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/services': RouteRecordInfo<
      '/monitoring/services',
      '/monitoring/services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitoring/troubleshoot': RouteRecordInfo<
      '/monitoring/troubleshoot',
      '/monitoring/troubleshoot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/no-permissions': RouteRecordInfo<
      '/no-permissions',
      '/no-permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations': RouteRecordInfo<
      '/operations',
      '/operations',
      Record<never, never>,
      Record<never, never>,
      | '/operations/'
      | '/operations/backups'
      | '/operations/device-auth'
      | '/operations/device-auth/'
      | '/operations/device-auth/certificates'
      | '/operations/firmware'
      | '/operations/jobs'
    >,
    '/operations/': RouteRecordInfo<
      '/operations/',
      '/operations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/backups': RouteRecordInfo<
      '/operations/backups',
      '/operations/backups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/device-auth': RouteRecordInfo<
      '/operations/device-auth',
      '/operations/device-auth',
      Record<never, never>,
      Record<never, never>,
      | '/operations/device-auth/'
      | '/operations/device-auth/certificates'
    >,
    '/operations/device-auth/': RouteRecordInfo<
      '/operations/device-auth/',
      '/operations/device-auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/device-auth/certificates': RouteRecordInfo<
      '/operations/device-auth/certificates',
      '/operations/device-auth/certificates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/firmware': RouteRecordInfo<
      '/operations/firmware',
      '/operations/firmware',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/jobs': RouteRecordInfo<
      '/operations/jobs',
      '/operations/jobs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organize': RouteRecordInfo<
      '/organize',
      '/organize',
      Record<never, never>,
      Record<never, never>,
      | '/organize/groups/'
      | '/organize/locations/'
      | '/organize/locations/[id]'
      | '/organize/tags/'
      | '/organize/tags/[id]'
    >,
    '/organize/groups/': RouteRecordInfo<
      '/organize/groups/',
      '/organize/groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organize/locations/': RouteRecordInfo<
      '/organize/locations/',
      '/organize/locations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organize/locations/[id]': RouteRecordInfo<
      '/organize/locations/[id]',
      '/organize/locations/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/organize/tags/': RouteRecordInfo<
      '/organize/tags/',
      '/organize/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organize/tags/[id]': RouteRecordInfo<
      '/organize/tags/[id]',
      '/organize/tags/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/'
      | '/settings/BrandingAssetsSection'
      | '/settings/BrandingDomainSection'
      | '/settings/BrandingLoginTextSection'
      | '/settings/BrandingMailTemplateSection'
      | '/settings/BrandingMessageTextSection'
      | '/settings/BrandingNotificationSection'
      | '/settings/BrandingPolicySection'
      | '/settings/BrandingPrivacySection'
      | '/settings/BrandingRestrictionsSection'
      | '/settings/app'
      | '/settings/authz-simulator'
      | '/settings/branding'
      | '/settings/configurations'
      | '/settings/identity-policies'
      | '/settings/identity-smtp'
      | '/settings/instance'
      | '/settings/log'
      | '/settings/mail'
      | '/settings/personas'
      | '/settings/plugins'
      | '/settings/user'
      | '/settings/user-groups'
      | '/settings/users'
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/app': RouteRecordInfo<
      '/settings/app',
      '/settings/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/authz-simulator': RouteRecordInfo<
      '/settings/authz-simulator',
      '/settings/authz-simulator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/branding': RouteRecordInfo<
      '/settings/branding',
      '/settings/branding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingAssetsSection': RouteRecordInfo<
      '/settings/BrandingAssetsSection',
      '/settings/BrandingAssetsSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingDomainSection': RouteRecordInfo<
      '/settings/BrandingDomainSection',
      '/settings/BrandingDomainSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingLoginTextSection': RouteRecordInfo<
      '/settings/BrandingLoginTextSection',
      '/settings/BrandingLoginTextSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingMailTemplateSection': RouteRecordInfo<
      '/settings/BrandingMailTemplateSection',
      '/settings/BrandingMailTemplateSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingMessageTextSection': RouteRecordInfo<
      '/settings/BrandingMessageTextSection',
      '/settings/BrandingMessageTextSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingNotificationSection': RouteRecordInfo<
      '/settings/BrandingNotificationSection',
      '/settings/BrandingNotificationSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingPolicySection': RouteRecordInfo<
      '/settings/BrandingPolicySection',
      '/settings/BrandingPolicySection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingPrivacySection': RouteRecordInfo<
      '/settings/BrandingPrivacySection',
      '/settings/BrandingPrivacySection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/BrandingRestrictionsSection': RouteRecordInfo<
      '/settings/BrandingRestrictionsSection',
      '/settings/BrandingRestrictionsSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/configurations': RouteRecordInfo<
      '/settings/configurations',
      '/settings/configurations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/identity-policies': RouteRecordInfo<
      '/settings/identity-policies',
      '/settings/identity-policies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/identity-smtp': RouteRecordInfo<
      '/settings/identity-smtp',
      '/settings/identity-smtp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/instance': RouteRecordInfo<
      '/settings/instance',
      '/settings/instance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/log': RouteRecordInfo<
      '/settings/log',
      '/settings/log',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/mail': RouteRecordInfo<
      '/settings/mail',
      '/settings/mail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/personas': RouteRecordInfo<
      '/settings/personas',
      '/settings/personas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/plugins': RouteRecordInfo<
      '/settings/plugins',
      '/settings/plugins',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/user': RouteRecordInfo<
      '/settings/user',
      '/settings/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/user-groups': RouteRecordInfo<
      '/settings/user-groups',
      '/settings/user-groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/users': RouteRecordInfo<
      '/settings/users',
      '/settings/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/waiting-room': RouteRecordInfo<
      '/waiting-room',
      '/waiting-room',
      Record<never, never>,
      Record<never, never>,
      | '/waiting-room/'
      | '/waiting-room/denied'
    >,
    '/waiting-room/': RouteRecordInfo<
      '/waiting-room/',
      '/waiting-room',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/waiting-room/denied': RouteRecordInfo<
      '/waiting-room/denied',
      '/waiting-room/denied',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/alerts.vue': {
      routes:
        | '/alerts'
        | '/alerts/'
        | '/alerts/channels/'
        | '/alerts/channels/[id]'
        | '/alerts/destinations/[id]'
        | '/alerts/rules/'
        | '/alerts/rules/[id]'
        | '/alerts/templates'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/alerts/index.vue': {
      routes:
        | '/alerts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/alerts/channels/index.vue': {
      routes:
        | '/alerts/channels/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/alerts/channels/[id].vue': {
      routes:
        | '/alerts/channels/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/alerts/destinations/[id].vue': {
      routes:
        | '/alerts/destinations/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/alerts/rules/index.vue': {
      routes:
        | '/alerts/rules/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/alerts/rules/[id].vue': {
      routes:
        | '/alerts/rules/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/alerts/templates.vue': {
      routes:
        | '/alerts/templates'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/signinwin/zitadel.vue': {
      routes:
        | '/auth/signinwin/zitadel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/automations.vue': {
      routes:
        | '/automations'
        | '/automations/'
        | '/automations/actions'
        | '/automations/grafana'
        | '/automations/node-red'
        | '/automations/variables'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/automations/index.vue': {
      routes:
        | '/automations/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/automations/actions.vue': {
      routes:
        | '/automations/actions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/automations/grafana.vue': {
      routes:
        | '/automations/grafana'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/automations/node-red.vue': {
      routes:
        | '/automations/node-red'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/automations/variables.vue': {
      routes:
        | '/automations/variables'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/callback.vue': {
      routes:
        | '/callback'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dash.vue': {
      routes:
        | '/dash'
        | '/dash/'
        | '/dash/[id]'
        | '/dash/analytics/[id]'
        | '/dash/control/[id]'
        | '/dash/energy/[id]'
        | '/dash/environment/[id]'
        | '/dash/manage'
        | '/dash/map/[id]'
        | '/dash/overview/[id]'
        | '/dash/safety/[id]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dash/index.vue': {
      routes:
        | '/dash/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dash/[id].vue': {
      routes:
        | '/dash/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/analytics/[id].vue': {
      routes:
        | '/dash/analytics/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/control/[id].vue': {
      routes:
        | '/dash/control/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/energy/[id].vue': {
      routes:
        | '/dash/energy/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/environment/[id].vue': {
      routes:
        | '/dash/environment/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/manage.vue': {
      routes:
        | '/dash/manage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dash/map/[id].vue': {
      routes:
        | '/dash/map/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/overview/[id].vue': {
      routes:
        | '/dash/overview/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dash/safety/[id].vue': {
      routes:
        | '/dash/safety/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/devices.vue': {
      routes:
        | '/devices'
        | '/devices/'
        | '/devices/discovered'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/devices/index.vue': {
      routes:
        | '/devices/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/devices/discovered.vue': {
      routes:
        | '/devices/discovered'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring.vue': {
      routes:
        | '/monitoring'
        | '/monitoring/'
        | '/monitoring/activity'
        | '/monitoring/audit-log'
        | '/monitoring/commands'
        | '/monitoring/connections'
        | '/monitoring/control-panel'
        | '/monitoring/database'
        | '/monitoring/device-ingest'
        | '/monitoring/events'
        | '/monitoring/host'
        | '/monitoring/investigate'
        | '/monitoring/logs'
        | '/monitoring/overview'
        | '/monitoring/resources'
        | '/monitoring/runtime'
        | '/monitoring/services'
        | '/monitoring/troubleshoot'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/monitoring/index.vue': {
      routes:
        | '/monitoring/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/activity.vue': {
      routes:
        | '/monitoring/activity'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/audit-log.vue': {
      routes:
        | '/monitoring/audit-log'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/commands.vue': {
      routes:
        | '/monitoring/commands'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/connections.vue': {
      routes:
        | '/monitoring/connections'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/control-panel.vue': {
      routes:
        | '/monitoring/control-panel'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/database.vue': {
      routes:
        | '/monitoring/database'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/device-ingest.vue': {
      routes:
        | '/monitoring/device-ingest'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/events.vue': {
      routes:
        | '/monitoring/events'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/host.vue': {
      routes:
        | '/monitoring/host'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/investigate.vue': {
      routes:
        | '/monitoring/investigate'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/logs.vue': {
      routes:
        | '/monitoring/logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/overview.vue': {
      routes:
        | '/monitoring/overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/resources.vue': {
      routes:
        | '/monitoring/resources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/runtime.vue': {
      routes:
        | '/monitoring/runtime'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/services.vue': {
      routes:
        | '/monitoring/services'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monitoring/troubleshoot.vue': {
      routes:
        | '/monitoring/troubleshoot'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/no-permissions.vue': {
      routes:
        | '/no-permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations.vue': {
      routes:
        | '/operations'
        | '/operations/'
        | '/operations/backups'
        | '/operations/device-auth'
        | '/operations/device-auth/'
        | '/operations/device-auth/certificates'
        | '/operations/firmware'
        | '/operations/jobs'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/operations/index.vue': {
      routes:
        | '/operations/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/backups.vue': {
      routes:
        | '/operations/backups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/device-auth.vue': {
      routes:
        | '/operations/device-auth'
        | '/operations/device-auth/'
        | '/operations/device-auth/certificates'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/operations/device-auth/index.vue': {
      routes:
        | '/operations/device-auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/device-auth/certificates.vue': {
      routes:
        | '/operations/device-auth/certificates'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/firmware.vue': {
      routes:
        | '/operations/firmware'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/jobs.vue': {
      routes:
        | '/operations/jobs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/organize.vue': {
      routes:
        | '/organize'
        | '/organize/groups/'
        | '/organize/locations/'
        | '/organize/locations/[id]'
        | '/organize/tags/'
        | '/organize/tags/[id]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/organize/groups/index.vue': {
      routes:
        | '/organize/groups/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/organize/locations/index.vue': {
      routes:
        | '/organize/locations/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/organize/locations/[id].vue': {
      routes:
        | '/organize/locations/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/organize/tags/index.vue': {
      routes:
        | '/organize/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/organize/tags/[id].vue': {
      routes:
        | '/organize/tags/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/'
        | '/settings/BrandingAssetsSection'
        | '/settings/BrandingDomainSection'
        | '/settings/BrandingLoginTextSection'
        | '/settings/BrandingMailTemplateSection'
        | '/settings/BrandingMessageTextSection'
        | '/settings/BrandingNotificationSection'
        | '/settings/BrandingPolicySection'
        | '/settings/BrandingPrivacySection'
        | '/settings/BrandingRestrictionsSection'
        | '/settings/app'
        | '/settings/authz-simulator'
        | '/settings/branding'
        | '/settings/configurations'
        | '/settings/identity-policies'
        | '/settings/identity-smtp'
        | '/settings/instance'
        | '/settings/log'
        | '/settings/mail'
        | '/settings/personas'
        | '/settings/plugins'
        | '/settings/user'
        | '/settings/user-groups'
        | '/settings/users'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/app.vue': {
      routes:
        | '/settings/app'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/authz-simulator.vue': {
      routes:
        | '/settings/authz-simulator'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/branding.vue': {
      routes:
        | '/settings/branding'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingAssetsSection.vue': {
      routes:
        | '/settings/BrandingAssetsSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingDomainSection.vue': {
      routes:
        | '/settings/BrandingDomainSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingLoginTextSection.vue': {
      routes:
        | '/settings/BrandingLoginTextSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingMailTemplateSection.vue': {
      routes:
        | '/settings/BrandingMailTemplateSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingMessageTextSection.vue': {
      routes:
        | '/settings/BrandingMessageTextSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingNotificationSection.vue': {
      routes:
        | '/settings/BrandingNotificationSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingPolicySection.vue': {
      routes:
        | '/settings/BrandingPolicySection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingPrivacySection.vue': {
      routes:
        | '/settings/BrandingPrivacySection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/BrandingRestrictionsSection.vue': {
      routes:
        | '/settings/BrandingRestrictionsSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/configurations.vue': {
      routes:
        | '/settings/configurations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/identity-policies.vue': {
      routes:
        | '/settings/identity-policies'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/identity-smtp.vue': {
      routes:
        | '/settings/identity-smtp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/instance.vue': {
      routes:
        | '/settings/instance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/log.vue': {
      routes:
        | '/settings/log'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/mail.vue': {
      routes:
        | '/settings/mail'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/personas.vue': {
      routes:
        | '/settings/personas'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/plugins.vue': {
      routes:
        | '/settings/plugins'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/user.vue': {
      routes:
        | '/settings/user'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/user-groups.vue': {
      routes:
        | '/settings/user-groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/users.vue': {
      routes:
        | '/settings/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/waiting-room.vue': {
      routes:
        | '/waiting-room'
        | '/waiting-room/'
        | '/waiting-room/denied'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/waiting-room/index.vue': {
      routes:
        | '/waiting-room/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/waiting-room/denied.vue': {
      routes:
        | '/waiting-room/denied'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
