/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/auth/signinwin/zitadel': RouteRecordInfo<'/auth/signinwin/zitadel', '/auth/signinwin/zitadel', Record<never, never>, Record<never, never>>,
    '/automations': RouteRecordInfo<'/automations', '/automations', Record<never, never>, Record<never, never>>,
    '/automations/': RouteRecordInfo<'/automations/', '/automations', Record<never, never>, Record<never, never>>,
    '/automations/actions': RouteRecordInfo<'/automations/actions', '/automations/actions', Record<never, never>, Record<never, never>>,
    '/automations/node-red': RouteRecordInfo<'/automations/node-red', '/automations/node-red', Record<never, never>, Record<never, never>>,
    '/callback': RouteRecordInfo<'/callback', '/callback', Record<never, never>, Record<never, never>>,
    '/dash': RouteRecordInfo<'/dash', '/dash', Record<never, never>, Record<never, never>>,
    '/dash/': RouteRecordInfo<'/dash/', '/dash', Record<never, never>, Record<never, never>>,
    '/dash/[id]': RouteRecordInfo<'/dash/[id]', '/dash/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dash/analytics/[id]': RouteRecordInfo<'/dash/analytics/[id]', '/dash/analytics/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/devices': RouteRecordInfo<'/devices', '/devices', Record<never, never>, Record<never, never>>,
    '/devices/': RouteRecordInfo<'/devices/', '/devices', Record<never, never>, Record<never, never>>,
    '/devices/backups': RouteRecordInfo<'/devices/backups', '/devices/backups', Record<never, never>, Record<never, never>>,
    '/devices/discovered': RouteRecordInfo<'/devices/discovered', '/devices/discovered', Record<never, never>, Record<never, never>>,
    '/devices/entities': RouteRecordInfo<'/devices/entities', '/devices/entities', Record<never, never>, Record<never, never>>,
    '/devices/firmware': RouteRecordInfo<'/devices/firmware', '/devices/firmware', Record<never, never>, Record<never, never>>,
    '/devices/groups/': RouteRecordInfo<'/devices/groups/', '/devices/groups', Record<never, never>, Record<never, never>>,
    '/devices/groups/[id]': RouteRecordInfo<'/devices/groups/[id]', '/devices/groups/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/devices/waiting-room': RouteRecordInfo<'/devices/waiting-room', '/devices/waiting-room', Record<never, never>, Record<never, never>>,
    '/graphs/': RouteRecordInfo<'/graphs/', '/graphs', Record<never, never>, Record<never, never>>,
    '/graphs/main': RouteRecordInfo<'/graphs/main', '/graphs/main', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/monitoring': RouteRecordInfo<'/monitoring', '/monitoring', Record<never, never>, Record<never, never>>,
    '/monitoring/': RouteRecordInfo<'/monitoring/', '/monitoring', Record<never, never>, Record<never, never>>,
    '/monitoring/audit-log': RouteRecordInfo<'/monitoring/audit-log', '/monitoring/audit-log', Record<never, never>, Record<never, never>>,
    '/monitoring/commands': RouteRecordInfo<'/monitoring/commands', '/monitoring/commands', Record<never, never>, Record<never, never>>,
    '/monitoring/control-panel': RouteRecordInfo<'/monitoring/control-panel', '/monitoring/control-panel', Record<never, never>, Record<never, never>>,
    '/monitoring/database': RouteRecordInfo<'/monitoring/database', '/monitoring/database', Record<never, never>, Record<never, never>>,
    '/monitoring/device-ingest': RouteRecordInfo<'/monitoring/device-ingest', '/monitoring/device-ingest', Record<never, never>, Record<never, never>>,
    '/monitoring/events': RouteRecordInfo<'/monitoring/events', '/monitoring/events', Record<never, never>, Record<never, never>>,
    '/monitoring/logs': RouteRecordInfo<'/monitoring/logs', '/monitoring/logs', Record<never, never>, Record<never, never>>,
    '/monitoring/overview': RouteRecordInfo<'/monitoring/overview', '/monitoring/overview', Record<never, never>, Record<never, never>>,
    '/monitoring/services': RouteRecordInfo<'/monitoring/services', '/monitoring/services', Record<never, never>, Record<never, never>>,
    '/no-permissions': RouteRecordInfo<'/no-permissions', '/no-permissions', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/settings/accounts': RouteRecordInfo<'/settings/accounts', '/settings/accounts', Record<never, never>, Record<never, never>>,
    '/settings/action_variables': RouteRecordInfo<'/settings/action_variables', '/settings/action_variables', Record<never, never>, Record<never, never>>,
    '/settings/app': RouteRecordInfo<'/settings/app', '/settings/app', Record<never, never>, Record<never, never>>,
    '/settings/audit-log': RouteRecordInfo<'/settings/audit-log', '/settings/audit-log', Record<never, never>, Record<never, never>>,
    '/settings/configurations': RouteRecordInfo<'/settings/configurations', '/settings/configurations', Record<never, never>, Record<never, never>>,
    '/settings/configurations_old': RouteRecordInfo<'/settings/configurations_old', '/settings/configurations_old', Record<never, never>, Record<never, never>>,
    '/settings/log': RouteRecordInfo<'/settings/log', '/settings/log', Record<never, never>, Record<never, never>>,
    '/settings/mail': RouteRecordInfo<'/settings/mail', '/settings/mail', Record<never, never>, Record<never, never>>,
    '/settings/plugins': RouteRecordInfo<'/settings/plugins', '/settings/plugins', Record<never, never>, Record<never, never>>,
    '/settings/user': RouteRecordInfo<'/settings/user', '/settings/user', Record<never, never>, Record<never, never>>,
    '/settings/users': RouteRecordInfo<'/settings/users', '/settings/users', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
