// Bundled IR starter catalog: curated Flipper-IRDB remotes (CC0-1.0),
// generated by scripts/build-ir-catalog.ts and committed under
// static/ir-catalog/. Read once per process from disk (cwd-rooted, same
// layout in dev and in the image); a missing or corrupt pack fails loud —
// the catalog is part of the build, never fetched at runtime.

import {readFileSync} from 'node:fs';
import path from 'node:path';

export interface CatalogRemote {
    id: string;
    name: string;
    brand: string;
    deviceType: string;
    codeCount: number;
    protocols: string[];
    sourceRepo: string;
    sourcePath: string;
    license: string;
    /** Raw Flipper .ir file text — parsed by the standard import parser. */
    content: string;
}

export interface CatalogSource {
    repo: string;
    commit: string;
    license: string;
    licenseNote: string;
}

interface CatalogFile {
    source: CatalogSource;
    remotes: CatalogRemote[];
}

export interface CatalogFilters {
    query?: string;
    brand?: string;
    deviceType?: string;
}

const DEFAULT_CATALOG_PATH = path.join(
    process.cwd(),
    'static/ir-catalog/catalog.json'
);

let catalogPath = DEFAULT_CATALOG_PATH;
let cached: CatalogFile | null = null;

function assertString(value: unknown, field: string): void {
    if (typeof value !== 'string' || value === '') {
        throw new Error(`ir catalog: missing or empty "${field}"`);
    }
}

function assertCatalogShape(raw: unknown): asserts raw is CatalogFile {
    const file = raw as Partial<CatalogFile> | null;
    if (!file || typeof file !== 'object') {
        throw new Error('ir catalog: not an object');
    }
    const source = file.source as Partial<CatalogSource> | undefined;
    assertString(source?.repo, 'source.repo');
    assertString(source?.commit, 'source.commit');
    assertString(source?.license, 'source.license');
    if (!Array.isArray(file.remotes) || file.remotes.length === 0) {
        throw new Error('ir catalog: "remotes" missing or empty');
    }
    for (const remote of file.remotes) {
        assertString(remote?.id, 'remote.id');
        assertString(remote?.name, `remote ${remote?.id}: name`);
        assertString(remote?.brand, `remote ${remote?.id}: brand`);
        assertString(remote?.deviceType, `remote ${remote?.id}: deviceType`);
        assertString(remote?.sourcePath, `remote ${remote?.id}: sourcePath`);
        assertString(remote?.license, `remote ${remote?.id}: license`);
        assertString(remote?.content, `remote ${remote?.id}: content`);
        if (!Number.isInteger(remote?.codeCount) || remote.codeCount < 1) {
            throw new Error(`ir catalog: remote ${remote?.id}: bad codeCount`);
        }
    }
}

function loadCatalogOnce(): CatalogFile {
    if (cached) return cached;
    let raw: unknown;
    try {
        raw = JSON.parse(readFileSync(catalogPath, 'utf8'));
    } catch (err: unknown) {
        const cause = err instanceof Error ? err.message : String(err);
        throw new Error(`ir catalog unreadable at ${catalogPath}: ${cause}`);
    }
    assertCatalogShape(raw);
    cached = raw;
    return cached;
}

export function catalogSource(): CatalogSource {
    return loadCatalogOnce().source;
}

export function getCatalogRemote(id: string): CatalogRemote | undefined {
    return loadCatalogOnce().remotes.find((remote) => remote.id === id);
}

/** Case-insensitive browse: substring query, exact brand/deviceType. */
export function searchCatalog(filters: CatalogFilters): CatalogRemote[] {
    const query = filters.query?.trim().toLowerCase();
    const brand = filters.brand?.trim().toLowerCase();
    const deviceType = filters.deviceType?.trim().toLowerCase();
    return loadCatalogOnce().remotes.filter((remote) => {
        if (brand && remote.brand.toLowerCase() !== brand) return false;
        if (deviceType && remote.deviceType.toLowerCase() !== deviceType) {
            return false;
        }
        if (!query) return true;
        return [remote.name, remote.brand, remote.deviceType].some((field) =>
            field.toLowerCase().includes(query)
        );
    });
}

/** Test seam: point the loader at a fixture pack (undefined = default). */
export function __setCatalogPathForTests(fixturePath?: string): void {
    catalogPath = fixturePath ?? DEFAULT_CATALOG_PATH;
    cached = null;
}
