# lib/state.sh — password generation, env save/load, init SQL, retention, keypairs

load_state_env() {
    if [ -f "$STATE_DIR/.env" ]; then
        # shellcheck source=/dev/null
        source "$STATE_DIR/.env"
        export POSTGRES_PASSWORD ZITADEL_POSTGRES_PASSWORD ZITADEL_DB_USER_PASSWORD
        export ZITADEL_ADMIN_PASSWORD ZITADEL_MASTERKEY
    fi
}

save_deploy_meta() {
    local hostname="${1:-${DEPLOY_HOSTNAME:-localhost}}"
    local command="${2:-up}"
    mkdir -p "$STATE_DIR"

    cat > "$DEPLOY_META_FILE" <<EOF
# Auto-generated by deploy-public.sh — do not edit manually
DEPLOY_LAST_COMMAND=${command}
DEPLOY_TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
DEPLOY_WITH_MDNS=${WITH_MDNS}
DEPLOY_WITH_SSL=${WITH_SSL}
DEPLOY_SSL_MODE=${SSL_MODE}
DEPLOY_SSL_DOMAIN=${SSL_DOMAIN}
DEPLOY_SSL_EMAIL=${SSL_EMAIL}
DEPLOY_HOSTNAME=${hostname}
DEPLOY_ZITADEL_HOSTNAME=${ZITADEL_HOSTNAME:-$hostname}
DEPLOY_ZITADEL_EXTERNALPORT=${ZITADEL_EXTERNALPORT}
DEPLOY_FLEET_MANAGER_PORT=${FLEET_MANAGER_PORT}
DEPLOY_COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
DEPLOY_WITH_LOGGING=${WITH_LOGGING}
EOF

    chmod 0600 "$DEPLOY_META_FILE"
}

load_deploy_meta() {
    [ -f "$DEPLOY_META_FILE" ] || return 0

    # shellcheck source=/dev/null
    source "$DEPLOY_META_FILE"

    if [ "$WITH_MDNS" != "true" ] && [ "${DEPLOY_WITH_MDNS:-false}" = "true" ]; then
        WITH_MDNS="true"
    fi
    if [ "$WITH_SSL" != "true" ] && [ "${DEPLOY_WITH_SSL:-false}" = "true" ]; then
        WITH_SSL="true"
    fi
    if [ -z "$SSL_MODE" ] && [ -n "${DEPLOY_SSL_MODE:-}" ]; then
        SSL_MODE="$DEPLOY_SSL_MODE"
    fi
    if [ -z "$SSL_DOMAIN" ] && [ -n "${DEPLOY_SSL_DOMAIN:-}" ]; then
        SSL_DOMAIN="$DEPLOY_SSL_DOMAIN"
    fi
    if [ -z "$SSL_EMAIL" ] && [ -n "${DEPLOY_SSL_EMAIL:-}" ]; then
        SSL_EMAIL="$DEPLOY_SSL_EMAIL"
    fi
    if [ -n "${DEPLOY_ZITADEL_HOSTNAME:-}" ]; then
        ZITADEL_HOSTNAME="$DEPLOY_ZITADEL_HOSTNAME"
    elif [ -n "${DEPLOY_HOSTNAME:-}" ]; then
        ZITADEL_HOSTNAME="$DEPLOY_HOSTNAME"
    fi
    [ -n "${DEPLOY_ZITADEL_EXTERNALPORT:-}" ] && ZITADEL_EXTERNALPORT="$DEPLOY_ZITADEL_EXTERNALPORT" || true
    [ -n "${DEPLOY_FLEET_MANAGER_PORT:-}" ] && FLEET_MANAGER_PORT="$DEPLOY_FLEET_MANAGER_PORT" || true
    [ -n "${DEPLOY_COMPOSE_PROJECT_NAME:-}" ] && COMPOSE_PROJECT_NAME="$DEPLOY_COMPOSE_PROJECT_NAME" || true
    if [ "$WITH_LOGGING" != "true" ] && [ "${DEPLOY_WITH_LOGGING:-false}" = "true" ]; then
        WITH_LOGGING="true"
    fi
    ZITADEL_EXTERNALSECURE="$WITH_SSL"
    export ZITADEL_HOSTNAME ZITADEL_EXTERNALPORT FLEET_MANAGER_PORT COMPOSE_PROJECT_NAME ZITADEL_EXTERNALSECURE
}

generate_passwords() {
    # Use values from public.env (loaded above) or generate if not set.
    # On first run: public.env demo values are used for simplicity.
    # Users can override by setting env vars before running.
    : "${POSTGRES_PASSWORD:=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)}"
    : "${ZITADEL_POSTGRES_PASSWORD:=$POSTGRES_PASSWORD}"
    : "${ZITADEL_DB_USER_PASSWORD:=$POSTGRES_PASSWORD}"
    : "${ZITADEL_ADMIN_PASSWORD:=FleetDemo1234!}"
    : "${ZITADEL_MASTERKEY:=$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)}"

    export POSTGRES_PASSWORD ZITADEL_POSTGRES_PASSWORD ZITADEL_DB_USER_PASSWORD
    export ZITADEL_ADMIN_PASSWORD ZITADEL_MASTERKEY
}

save_env() {
    # Save passwords to state so they persist across restarts
    local env_file="$STATE_DIR/.env"
    mkdir -p "$STATE_DIR"

    if [ -f "$env_file" ]; then
        # Re-load existing passwords
        # shellcheck source=/dev/null
        source "$env_file"
        export POSTGRES_PASSWORD ZITADEL_POSTGRES_PASSWORD ZITADEL_DB_USER_PASSWORD
        export ZITADEL_ADMIN_PASSWORD ZITADEL_MASTERKEY
        info "Loaded existing configuration"
    else
        cat > "$env_file" <<EOF
# Auto-generated by deploy-public.sh — do not edit
# Delete this file + volumes to reset: ./deploy/deploy-public.sh down --volumes
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ZITADEL_POSTGRES_PASSWORD=${ZITADEL_POSTGRES_PASSWORD}
ZITADEL_DB_USER_PASSWORD=${ZITADEL_DB_USER_PASSWORD}
ZITADEL_ADMIN_PASSWORD=${ZITADEL_ADMIN_PASSWORD}
ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}
EOF
        chmod 0600 "$env_file"
        info "Generated new configuration"
    fi
}

generate_init_sql() {
    mkdir -p "$STATE_DIR"

    # Fleet DB init SQL
    cat > "$STATE_DIR/init-fleet-db.sql" <<'SQL'
-- Auto-generated by deploy-public.sh
CREATE SCHEMA IF NOT EXISTS migration;
SQL

    # Zitadel DB init SQL
    local escaped_pw="${ZITADEL_DB_USER_PASSWORD//\'/\'\'}"
    cat > "$STATE_DIR/init-zitadel-db.sql" <<SQL
-- Auto-generated by deploy-public.sh
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'zitadel') THEN
    CREATE USER zitadel WITH PASSWORD '${escaped_pw}';
  ELSE
    ALTER USER zitadel WITH PASSWORD '${escaped_pw}';
  END IF;
END
\$\$;
GRANT ALL PRIVILEGES ON DATABASE zitadel TO zitadel;
ALTER USER zitadel CREATEDB;
SQL

    chmod 0644 "$STATE_DIR/init-fleet-db.sql" "$STATE_DIR/init-zitadel-db.sql"
}

apply_retention_policies() {
    # Apply configurable retention policies to TimescaleDB hypertables.
    # Safe to run repeatedly — removes old policies before adding new ones.
    # Runs after DB is healthy and migrations have created the tables.

    local status_retention="${STATUS_RETENTION:-7 days}"
    local em_retention="${EM_STATS_RETENTION:-1 year}"
    local audit_retention="${AUDIT_LOG_RETENTION:-90 days}"

    info "Applying retention policies: status=${status_retention}, em=${em_retention}, audit=${audit_retention}"

    local sql
    sql=$(cat <<SQL
-- Auto-applied by deploy-public.sh
-- Idempotent: removes existing policies before re-adding

-- device.status — high-frequency telemetry (default: 24 hours)
DO \$\$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='device' AND table_name='status') THEN
    PERFORM remove_retention_policy('device.status', if_exists => true);
    PERFORM add_retention_policy('device.status', INTERVAL '${status_retention}');
    PERFORM remove_compression_policy('device.status', if_exists => true);
    PERFORM add_compression_policy('device.status', compress_created_before => INTERVAL '1 hour');
  END IF;
END \$\$;

-- device_em.stats — energy meter data (default: 1 year)
DO \$\$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='device_em' AND table_name='stats') THEN
    PERFORM remove_retention_policy('device_em.stats', if_exists => true);
    PERFORM add_retention_policy('device_em.stats', INTERVAL '${em_retention}');
    PERFORM remove_compression_policy('device_em.stats', if_exists => true);
    PERFORM add_compression_policy('device_em.stats', compress_created_before => INTERVAL '24 hours');
  END IF;
END \$\$;

-- logging.audit_log — user actions and RPC calls (default: 90 days)
DO \$\$ BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='logging' AND table_name='audit_log') THEN
    -- Ensure it's a hypertable (migration may not have set retention)
    PERFORM remove_retention_policy('logging.audit_log', if_exists => true);
    PERFORM add_retention_policy('logging.audit_log', INTERVAL '${audit_retention}');
  END IF;
END \$\$;
SQL
)

    # Execute via docker exec against the running fleet-db
    if echo "$sql" | docker exec -i "${COMPOSE_PROJECT_NAME}-fleet-db-1" \
        psql -U postgres -d fleet --no-psqlrc -q 2>/dev/null; then
        ok "Retention policies applied"
    else
        info "Retention policies will be applied after first restart (tables created during initial startup)"
    fi
}

generate_system_api_keypair() {
    local sa_dir="$STATE_DIR/system-api"
    mkdir -p "$sa_dir"
    chmod 0755 "$sa_dir"

    if [ -f "$sa_dir/system-user.pem" ] && [ -f "$sa_dir/system-user.pub" ]; then
        ok "System API keypair exists"
    else
        info "Generating RSA keypair for System API..."
        openssl genrsa -traditional -out "$sa_dir/system-user.pem" 2048 2>/dev/null
        openssl rsa -in "$sa_dir/system-user.pem" -outform PEM -pubout -out "$sa_dir/system-user.pub" 2>/dev/null
        chmod 0600 "$sa_dir/system-user.pem"
        ok "Keypair generated"
    fi

    # Always regenerate config
    cat > "$sa_dir/system-api-config.yaml" <<'EOF'
# Auto-generated by deploy-public.sh
SystemAPIUsers:
  - system-user-1:
      Path: /system-api/system-user.pub
EOF
    chmod 0644 "$sa_dir/system-api-config.yaml" "$sa_dir/system-user.pub"
}
