#!/usr/bin/env bash
#
# Generate RSA keypair and config for Zitadel System API
#
# This enables the bootstrap script to add custom instance domains,
# allowing Docker-internal container-to-container communication.
#
# Idempotent: only generates if keypair doesn't already exist.
#
# Output:
#   deploy/state/system-api/system-user.pem      — RSA private key
#   deploy/state/system-api/system-user.pub       — RSA public key
#   deploy/state/system-api/system-api-config.yaml — Zitadel config override
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

SYSTEM_API_DIR="$DEPLOY_DIR/state/system-api"
PRIVATE_KEY="$SYSTEM_API_DIR/system-user.pem"
PUBLIC_KEY="$SYSTEM_API_DIR/system-user.pub"
CONFIG_FILE="$SYSTEM_API_DIR/system-api-config.yaml"
SYSTEM_USER_NAME="system-user-1"

mkdir -p "$SYSTEM_API_DIR"
# Zitadel container (UID 1000) needs to read config + public key from this dir
chmod 0755 "$SYSTEM_API_DIR"

# Generate keypair if not exists
if [ -f "$PRIVATE_KEY" ] && [ -f "$PUBLIC_KEY" ]; then
    echo "  System API keypair already exists"
else
    echo "  Generating RSA keypair for System API..."
    # --traditional flag ensures PKCS1 format (required by Zitadel)
    openssl genrsa -traditional -out "$PRIVATE_KEY" 2048 2>/dev/null
    openssl rsa -in "$PRIVATE_KEY" -outform PEM -pubout -out "$PUBLIC_KEY" 2>/dev/null
    chmod 0600 "$PRIVATE_KEY"
    echo "  Keypair generated"
fi

# Default denylist minus 172.16.0.0/12 (Docker bridge FM runs on), defined once.
# Emitted to both HTTPClient.DenyList (Zitadel v4.15+) and the deprecated
# Actions.HTTP.DenyList (v3.x upgrade stage) so Action V2 reaches FM either way.
DENY_ENTRIES=(localhost 0.0.0.0/8 10.0.0.0/8 100.64.0.0/10 127.0.0.0/8 \
  169.254.0.0/16 192.168.0.0/16 198.18.0.0/15 ::/128 ::1/128 fc00::/7 fe80::/10)
emit_denylist() { local e; for e in "${DENY_ENTRIES[@]}"; do printf '%s- "%s"\n' "$1" "$e"; done; }

# Always regenerate config (in case paths change)
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by init-system-api.sh — do not edit manually
SystemAPIUsers:
  - ${SYSTEM_USER_NAME}:
      Path: /system-api/system-user.pub
      Memberships:
        - MemberType: System
          Roles:
            - "SYSTEM_OWNER"
HTTPClient:
  DenyList:
$(emit_denylist '    ')
Actions:
  HTTP:
    DenyList:
$(emit_denylist '      ')
# Telemetry to zitadel.com off by default.
ServicePing:
  Enabled: false
EOF

chmod 0644 "$CONFIG_FILE" "$PUBLIC_KEY"
echo "  Config written: $CONFIG_FILE"
