#!/usr/bin/env bash
#
# Generate Fleet DB init SQL with migration schema
#
# The migration-collection library expects the 'migration' schema to exist
# before it can track applied migrations. This script generates an init SQL
# that creates the schema on first PostgreSQL startup.
#
# Note: Postgres init SQL only runs on first startup (empty data volume).
#
# Usage: init-fleet-db.sh
# Output: deploy/state/init-fleet-db.sql

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
STATE_DIR="$DEPLOY_DIR/state"

mkdir -p "$STATE_DIR"

cat > "$STATE_DIR/init-fleet-db.sql" <<'SQL'
-- Auto-generated by init-fleet-db.sh — do not edit
-- Pre-create schemas needed by Fleet Manager's migration-collection library
CREATE SCHEMA IF NOT EXISTS migration;
SQL

chmod 0644 "$STATE_DIR/init-fleet-db.sql"
echo "Generated $STATE_DIR/init-fleet-db.sql"
