#!/usr/bin/env bash
# Materializes deploy-time secrets into deploy/state/.env from the configured vault.
#
# Backends (selected via FM_VAULT_BACKEND):
#   op   — 1Password CLI
#   vault — HashiCorp Vault KV v2
#   aws  — AWS Secrets Manager
#   env  — already-exported shell env (no-op fetch, just writes the file)
#
# Required env per backend:
#   op    — FM_VAULT_OP_ITEM (item title or vault path)
#   vault — FM_VAULT_ADDR + FM_VAULT_TOKEN + FM_VAULT_PATH (kv/data/...)
#   aws   — FM_VAULT_AWS_SECRET_ID
#
# Output: deploy/state/.env with chmod 0600 containing one KEY=value per line.

set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$DEPLOY_DIR/state/.env"
mkdir -p "$DEPLOY_DIR/state"

backend="${FM_VAULT_BACKEND:-env}"
keys=(
    ZITADEL_MASTERKEY
    ZITADEL_POSTGRES_PASSWORD
    ZITADEL_DB_USER_PASSWORD
    ZITADEL_ADMIN_PASSWORD
    POSTGRES_PASSWORD
    FM_SECRET_ENCRYPTION_KEY
    # Rotation envelope. KEY_ID is always required during a rotation;
    # the PREVIOUS pair is only set inside the rotation window. Missing
    # values are silently skipped by the materialiser so listing all
    # three here is safe outside rotation too. CR-13.
    FM_SECRET_ENCRYPTION_KEY_ID
    FM_SECRET_ENCRYPTION_KEY_PREVIOUS
    FM_SECRET_ENCRYPTION_KEY_PREVIOUS_ID
    FM_SECRET_KDF_SALT
    JWT_SECRET
    FM_ADMIN_PASSWORD
    FM_PLATFORM_ADMIN_PASSWORD
)

declare -A values

case "$backend" in
    op)
        : "${FM_VAULT_OP_ITEM:?FM_VAULT_OP_ITEM is required for backend=op}"
        for k in "${keys[@]}"; do
            v=$(op read "op://${FM_VAULT_OP_ITEM}/${k}" 2>/dev/null || true)
            [ -n "$v" ] && values[$k]="$v"
        done
        ;;
    vault)
        : "${FM_VAULT_ADDR:?required}" "${FM_VAULT_TOKEN:?required}" "${FM_VAULT_PATH:?required}"
        body=$(curl -sS -H "X-Vault-Token: $FM_VAULT_TOKEN" \
            "${FM_VAULT_ADDR%/}/v1/${FM_VAULT_PATH#/}")
        for k in "${keys[@]}"; do
            v=$(echo "$body" | jq -r ".data.data.${k} // empty")
            [ -n "$v" ] && values[$k]="$v"
        done
        ;;
    aws)
        : "${FM_VAULT_AWS_SECRET_ID:?required}"
        body=$(aws secretsmanager get-secret-value --secret-id "$FM_VAULT_AWS_SECRET_ID" --query SecretString --output text)
        for k in "${keys[@]}"; do
            v=$(echo "$body" | jq -r ".${k} // empty")
            [ -n "$v" ] && values[$k]="$v"
        done
        ;;
    env)
        for k in "${keys[@]}"; do
            v="${!k:-}"
            [ -n "$v" ] && values[$k]="$v"
        done
        ;;
    *)
        echo "Unknown FM_VAULT_BACKEND: $backend" >&2; exit 1 ;;
esac

if [ "${#values[@]}" -eq 0 ]; then
    echo "ERROR: no secrets resolved from backend=$backend" >&2
    exit 1
fi

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
echo "# Auto-generated by load-secrets.sh — do not commit" > "$tmp"
for k in "${!values[@]}"; do
    printf '%s=%s\n' "$k" "${values[$k]}" >> "$tmp"
done
chmod 0600 "$tmp"
mv "$tmp" "$OUT"
echo "Loaded ${#values[@]} secret(s) from $backend → $OUT"
