#!/usr/bin/env bash
# SoT for Zitadel names. Mirrors backend/src/modules/zitadelActions/eventNames.ts.

ZITADEL_EVT_USER_REMOVED=user.removed
ZITADEL_EVT_USER_HUMAN_ADDED=user.human.added
ZITADEL_EVT_USER_MACHINE_ADDED=user.machine.added
ZITADEL_EVT_USER_PAT_REMOVED=user.pat.removed
ZITADEL_EVT_USER_GRANT_CHANGED=user.grant.changed
ZITADEL_EVT_USER_GRANT_REMOVED=user.grant.removed
ZITADEL_EVT_USER_GRANT_CASCADE_REMOVED=user.grant.cascade.removed

ZITADEL_EVT_ORG_ADDED=org.added
ZITADEL_EVT_ORG_REMOVED=org.removed

ZITADEL_TARGET_SUFFIX_USER_REMOVED=-user-removed
ZITADEL_TARGET_SUFFIX_GRANT_REMOVED=-grant-removed

ZITADEL_ACTION_BINDINGS=(
    "gdpr:${ZITADEL_EVT_USER_REMOVED}"
    "grant:${ZITADEL_EVT_USER_GRANT_CHANGED}"
    "grant:${ZITADEL_EVT_USER_GRANT_REMOVED}"
    "grant:${ZITADEL_EVT_USER_GRANT_CASCADE_REMOVED}"
)

export ZITADEL_EVT_USER_REMOVED ZITADEL_EVT_USER_HUMAN_ADDED ZITADEL_EVT_USER_MACHINE_ADDED
export ZITADEL_EVT_USER_PAT_REMOVED ZITADEL_EVT_USER_GRANT_CHANGED
export ZITADEL_EVT_USER_GRANT_REMOVED ZITADEL_EVT_USER_GRANT_CASCADE_REMOVED
export ZITADEL_EVT_ORG_ADDED ZITADEL_EVT_ORG_REMOVED
export ZITADEL_TARGET_SUFFIX_USER_REMOVED ZITADEL_TARGET_SUFFIX_GRANT_REMOVED
