# shellcheck shell=bash

ZITADEL_SYSTEM_API_USER="${ZITADEL_SYSTEM_API_USER:-system-user-1}"
ZITADEL_SYSTEM_API_DENY_ENTRIES=(
    localhost
    0.0.0.0/8
    10.0.0.0/8
    100.64.0.0/10
    127.0.0.0/8
    169.254.0.0/16
    192.168.0.0/16
    198.18.0.0/15
    ::/128
    ::1/128
    fc00::/7
    fe80::/10
)

zitadel_emit_system_api_denylist() {
    local indent="$1" entry
    for entry in "${ZITADEL_SYSTEM_API_DENY_ENTRIES[@]}"; do
        printf '%s- "%s"\n' "$indent" "$entry"
    done
}

zitadel_write_system_api_config() {
    local config_file="$1"
    local public_key_path="$2"
    local generated_by="$3"

    cat > "$config_file" <<EOF
# Auto-generated by ${generated_by} — do not edit manually
SystemAPIUsers:
  - ${ZITADEL_SYSTEM_API_USER}:
      Path: ${public_key_path}
      Memberships:
        - MemberType: System
          Roles:
            - "SYSTEM_OWNER"
HTTPClient:
  DenyList:
$(zitadel_emit_system_api_denylist '    ')
Actions:
  HTTP:
    DenyList:
$(zitadel_emit_system_api_denylist '      ')
# Telemetry to zitadel.com off by default.
ServicePing:
  Enabled: false
EOF
}

zitadel_generate_system_api_files() {
    local system_api_dir="$1"
    local mounted_public_key_path="$2"
    local generated_by="$3"
    local private_key="$system_api_dir/system-user.pem"
    local public_key="$system_api_dir/system-user.pub"
    local config_file="$system_api_dir/system-api-config.yaml"

    mkdir -p "$system_api_dir"
    # Zitadel runs as UID 1000 and must read config + public key.
    chmod 0755 "$system_api_dir"

    if [ -f "$private_key" ] && [ -f "$public_key" ]; then
        echo "  System API keypair already exists"
    else
        echo "  Generating RSA keypair for System API..."
        openssl genrsa -traditional -out "$private_key" 2048 2>/dev/null
        openssl rsa -in "$private_key" -outform PEM -pubout -out "$public_key" 2>/dev/null
        chmod 0600 "$private_key"
        echo "  Keypair generated"
    fi

    zitadel_write_system_api_config \
        "$config_file" \
        "$mounted_public_key_path" \
        "$generated_by"
    chmod 0644 "$config_file" "$public_key"
    echo "  Config written: $config_file"
}
