# shellcheck shell=bash
# state/init-sql.sh — public deploy database init SQL.

generate_init_sql() {
    mkdir -p "$STATE_DIR"
    # Lock the secret dir to the owner; containers bind-mount as root and still
    # read the files via the mount. Files stay 0644 for the in-container user.
    chmod 0700 "$STATE_DIR"

    cat > "$STATE_DIR/init-fleet-db.sql" <<'SQL'
-- Auto-generated by deploy-public.sh
CREATE SCHEMA IF NOT EXISTS migration;
SQL

    local escaped_pw="${ZITADEL_DB_USER_PASSWORD//\'/\'\'}"
    cat > "$STATE_DIR/init-zitadel-db.sql" <<SQL
-- Auto-generated by deploy-public.sh
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'zitadel') THEN
    CREATE USER zitadel WITH PASSWORD '${escaped_pw}';
  ELSE
    ALTER USER zitadel WITH PASSWORD '${escaped_pw}';
  END IF;
END
\$\$;
ALTER DATABASE zitadel OWNER TO zitadel;
GRANT CONNECT, CREATE ON DATABASE zitadel TO zitadel;
GRANT ALL PRIVILEGES ON DATABASE zitadel TO zitadel;
ALTER USER zitadel CREATEDB;
SQL

    chmod 0644 "$STATE_DIR/init-fleet-db.sql" "$STATE_DIR/init-zitadel-db.sql"
}
