# shellcheck shell=bash
# state/meta.sh — public deploy command metadata.

save_deploy_meta() {
    local hostname="${1:-${DEPLOY_HOSTNAME:-localhost}}"
    local command="${2:-up}"
    mkdir -p "$STATE_DIR"

    cat > "$DEPLOY_META_FILE" <<EOF
# Auto-generated by deploy-public.sh — do not edit manually
DEPLOY_LAST_COMMAND=${command}
DEPLOY_TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
DEPLOY_WITH_MDNS=${WITH_MDNS}
DEPLOY_WITH_SSL=${WITH_SSL}
DEPLOY_SSL_MODE=${SSL_MODE}
DEPLOY_SSL_DOMAIN=${SSL_DOMAIN}
DEPLOY_SSL_EMAIL=${SSL_EMAIL}
DEPLOY_HOSTNAME=${hostname}
DEPLOY_ZITADEL_HOSTNAME=${ZITADEL_HOSTNAME:-$hostname}
DEPLOY_ZITADEL_EXTERNALPORT=${ZITADEL_EXTERNALPORT}
DEPLOY_ZITADEL_EXTERNALSECURE=${ZITADEL_EXTERNALSECURE:-false}
DEPLOY_ZITADEL_PUBLIC_SCHEME=${ZITADEL_PUBLIC_SCHEME:-}
DEPLOY_ZITADEL_TLS_MODE=${ZITADEL_TLS_MODE:-}
DEPLOY_FM_HOSTNAME=${FM_HOSTNAME:-$hostname}
DEPLOY_FLEET_MANAGER_PORT=${FLEET_MANAGER_PORT}
DEPLOY_COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
DEPLOY_WITH_LOGGING=${WITH_LOGGING}
DEPLOY_ENV=${DEPLOY_ENV:-public}
EOF

    chmod 0600 "$DEPLOY_META_FILE"
}

load_deploy_meta() {
    [ -f "$DEPLOY_META_FILE" ] || return 0

    # shellcheck source=/dev/null
    source "$DEPLOY_META_FILE"

    if [ "$WITH_MDNS" != "true" ] && [ "${DEPLOY_WITH_MDNS:-false}" = "true" ]; then
        WITH_MDNS="true"
    fi
    if [ "$WITH_SSL" != "true" ] && [ "${DEPLOY_WITH_SSL:-false}" = "true" ]; then
        WITH_SSL="true"
    fi
    if [ -z "$SSL_MODE" ] && [ -n "${DEPLOY_SSL_MODE:-}" ]; then
        SSL_MODE="$DEPLOY_SSL_MODE"
    fi
    if [ -z "$SSL_DOMAIN" ] && [ -n "${DEPLOY_SSL_DOMAIN:-}" ]; then
        SSL_DOMAIN="$DEPLOY_SSL_DOMAIN"
    fi
    if [ -z "$SSL_EMAIL" ] && [ -n "${DEPLOY_SSL_EMAIL:-}" ]; then
        SSL_EMAIL="$DEPLOY_SSL_EMAIL"
    fi
    if [ -n "${DEPLOY_ZITADEL_HOSTNAME:-}" ]; then
        ZITADEL_HOSTNAME="$DEPLOY_ZITADEL_HOSTNAME"
    elif [ -n "${DEPLOY_HOSTNAME:-}" ]; then
        ZITADEL_HOSTNAME="$DEPLOY_HOSTNAME"
    fi
    [ -n "${DEPLOY_ZITADEL_EXTERNALPORT:-}" ] && ZITADEL_EXTERNALPORT="$DEPLOY_ZITADEL_EXTERNALPORT" || true
    [ -n "${DEPLOY_FLEET_MANAGER_PORT:-}" ] && FLEET_MANAGER_PORT="$DEPLOY_FLEET_MANAGER_PORT" || true
    [ -n "${DEPLOY_COMPOSE_PROJECT_NAME:-}" ] && COMPOSE_PROJECT_NAME="$DEPLOY_COMPOSE_PROJECT_NAME" || true
    if [ "$WITH_LOGGING" != "true" ] && [ "${DEPLOY_WITH_LOGGING:-false}" = "true" ]; then
        WITH_LOGGING="true"
    fi
    # Migrate legacy state from pre-DEPLOY_ENV deploys (--quick → --env dev).
    if [ -z "${DEPLOY_ENV:-}" ] && [ "${DEPLOY_WITH_QUICK:-false}" = "true" ]; then
        DEPLOY_ENV="dev"
    fi
    # Single source: state's DEPLOY_ENV picks the env file; load_deploy_env_overrides
    # exports FM_DEV_MODE and other per-env vars into shell. Same path as `up`.
    DEPLOY_ENV="${DEPLOY_ENV:-public}"
    load_deploy_env_overrides
    ZITADEL_EXTERNALSECURE="$WITH_SSL"
    export ZITADEL_HOSTNAME ZITADEL_EXTERNALPORT FLEET_MANAGER_PORT COMPOSE_PROJECT_NAME ZITADEL_EXTERNALSECURE
}
