# shellcheck shell=bash
# Public-flow wrapper around common/secrets.sh + public-only System API keypair.

# shellcheck source=deploy/scripts/common/secrets.sh
source "$(dirname "${BASH_SOURCE[0]}")/../../../common/secrets.sh"

generate_system_api_keypair() {
    local sa_dir="$STATE_DIR/system-api"
    mkdir -p "$sa_dir"
    chmod 0755 "$sa_dir"

    if [ -f "$sa_dir/system-user.pem" ] && [ -f "$sa_dir/system-user.pub" ]; then
        ok "System API keypair exists"
    else
        info "Generating RSA keypair for System API..."
        openssl genrsa -traditional -out "$sa_dir/system-user.pem" 2048 2>/dev/null
        openssl rsa -in "$sa_dir/system-user.pem" -outform PEM -pubout -out "$sa_dir/system-user.pub" 2>/dev/null
        chmod 0600 "$sa_dir/system-user.pem"
        ok "Keypair generated"
    fi

    cat > "$sa_dir/system-api-config.yaml" <<'EOF'
# Auto-generated by deploy-public.sh
SystemAPIUsers:
  - system-user-1:
      Path: /system-api/system-user.pub
      Memberships:
        - MemberType: System
          Roles:
            - "SYSTEM_OWNER"
# Drop only 172.16/12 from the default deny list so Action V2 can reach FM.
Actions:
  HTTP:
    DenyList:
      - "127.0.0.0/8"
      - "10.0.0.0/8"
      - "192.168.0.0/16"
      - "::1/128"
      - "fc00::/7"
      - "fe80::/10"
      - "localhost"
# Telemetry to zitadel.com off by default.
ServicePing:
  Enabled: false
EOF
    chmod 0644 "$sa_dir/system-api-config.yaml" "$sa_dir/system-user.pub"
}
