--------------UP
-- Single source of truth for the built-in starter catalog (Rule.ListTemplates).
-- Supersedes the legacy built-in seeds from 6303 + 20012 (org_id IS NULL only;
-- never touches org-authored templates), and uses public component_* kinds.
-- Field paths verified against the Shelly API docs (em:0.total_act_power, not
-- the non-existent em:0.act_power).
-- Idempotent via the org-scoped unique index from 6532.

DELETE FROM notifications.alert_rule_templates
WHERE organization_id IS NULL
  AND template_key IN (
    'device-offline-critical', 'device-back-online', 'battery-low-warning',
    'battery-critical', 'smoke-alarm', 'flood-alarm', 'motion-detected',
    'firmware-update-failed', 'backup-failed', 'automation-run-failed',
    'relay-turned-on', 'relay-turned-off', 'cover-opened', 'cover-closed'
  );

INSERT INTO notifications.alert_rule_templates (
    template_key, category, label, description,
    kind, severity,
    config, dedupe_window_sec, cooldown_sec,
    summary_template, message_template, auto_resolve
) VALUES
    ('builtin:device_offline_5min', 'Connectivity',
     'Device offline > 5 minutes',
     'Fires when a device is offline for 5 minutes. A good everyday default.',
     'device_offline', 'warning',
     '{"offlineForSec":300}'::jsonb, 300, 1800,
     'Device {{device.name}} went offline',
     '{{device.name}} ({{device.shellyID}}) has been offline for over 5 minutes.',
     TRUE),

    ('builtin:device_offline_30min', 'Connectivity',
     'Device offline > 30 minutes',
     'Fires when a device stays offline for 30 minutes. For important equipment.',
     'device_offline', 'critical',
     '{"offlineForSec":1800}'::jsonb, 1800, 3600,
     'CRITICAL: {{device.name}} offline > 30 min',
     '{{device.name}} ({{device.shellyID}}) has been offline for over 30 minutes.',
     TRUE),

    ('builtin:device_offline_immediate', 'Connectivity',
     'Device offline - no debounce',
     'Fires the moment a device goes offline, with no delay.',
     'device_offline', 'critical',
     '{"offlineForSec":30}'::jsonb, 0, 600,
     'CRITICAL: {{device.name}} dropped offline',
     '{{device.name}} ({{device.shellyID}}) went offline.',
     TRUE),

    ('builtin:device_back_online', 'Connectivity',
     'Device recovered',
     'Fires when a device starts reporting again after being offline.',
     'device_back_online', 'info',
     '{}'::jsonb, 60, 0,
     '{{device.name}} is back online',
     '{{device.name}} ({{device.shellyID}}) is reporting again.',
     TRUE),

    ('builtin:battery_below_20', 'Power',
     'Battery below 20%',
     'Fires when battery drops below 20%, leaving time to recharge.',
     'battery_below', 'warning',
     '{"thresholdPct":20}'::jsonb, 21600, 86400,
     'Battery low on {{device.name}}',
     '{{device.name}} battery is below 20%. Plan a swap soon.',
     TRUE),

    ('builtin:battery_below_5', 'Power',
     'Battery below 5%',
     'Fires when battery is nearly empty, below 5%.',
     'battery_below', 'critical',
     '{"thresholdPct":5}'::jsonb, 21600, 86400,
     'CRITICAL: battery < 5% on {{device.name}}',
     '{{device.name}} battery is below 5%. Recharge now.',
     TRUE),

    ('builtin:smoke_alarm_any', 'Safety',
     'Any smoke alarm',
     'Fires the instant any smoke detector goes into alarm.',
     'smoke_alarm', 'critical',
     '{}'::jsonb, 0, 300,
     'SMOKE ALARM at {{device.name}}',
     'A smoke detector at {{device.name}} ({{device.shellyID}}) is in alarm.',
     TRUE),

    ('builtin:flood_alarm_any', 'Safety',
     'Any flood detected',
     'Fires the instant a water sensor detects a leak.',
     'flood_alarm', 'critical',
     '{}'::jsonb, 0, 300,
     'FLOOD detected at {{device.name}}',
     'A water sensor at {{device.name}} ({{device.shellyID}}) detected flooding.',
     TRUE),

    ('builtin:motion_detected', 'Activity',
     'Motion or presence detected',
     'Fires when a sensor detects motion or presence.',
     'motion_detected', 'warning',
     '{"clearTimeoutSec":300}'::jsonb, 60, 300,
     'Motion at {{device.name}}',
     'Motion or presence detected at {{device.name}} ({{device.shellyID}}).',
     TRUE),

    ('builtin:motion_restricted_area', 'Activity',
     'Motion in restricted area',
     'Fires on motion in an area that should stay empty.',
     'motion_detected', 'critical',
     '{"clearTimeoutSec":180}'::jsonb, 0, 180,
     'INTRUSION: motion at {{device.name}}',
     'Motion detected in a restricted area: {{device.name}}.',
     TRUE),

    ('builtin:temp_above_30c', 'Environment',
     'Temperature above 30 C',
     'Fires when a temperature sensor reads above 30 C.',
     'component_threshold', 'warning',
     '{"component":"temperature:0","field":"tC","operator":"gt","threshold":30}'::jsonb, 300, 1800,
     'High temperature at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported temperature above 30 C.',
     TRUE),

    ('builtin:temp_below_5c_freezer', 'Environment',
     'Temperature below 5 C (freezer)',
     'Fires when a freezer warms above 5 C, risking spoilage.',
     'component_threshold', 'warning',
     '{"component":"temperature:0","field":"tC","operator":"lt","threshold":5}'::jsonb, 300, 1800,
     'Cold-chain break at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) dropped below the 5 C freezer floor.',
     TRUE),

    ('builtin:humidity_above_70', 'Environment',
     'Humidity above 70%',
     'Fires when a humidity sensor reads above 70%.',
     'component_threshold', 'info',
     '{"component":"humidity:0","field":"rh","operator":"gt","threshold":70}'::jsonb, 600, 3600,
     'High humidity at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported humidity above 70%.',
     TRUE),

    ('builtin:pressure_above_1050hpa', 'Environment',
     'Pressure above 1050 hPa',
     'Fires when a pressure sensor reads above 1050 hPa.',
     'component_threshold', 'info',
     '{"component":"pressure:0","field":"pressure","operator":"gt","threshold":1050}'::jsonb, 600, 3600,
     'High pressure at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported pressure above 1050 hPa.',
     TRUE),

    ('builtin:co2_above_1000ppm', 'Air Quality',
     'CO2 above 1000 ppm',
     'Fires when a CO2 sensor reads above 1000 ppm.',
     'component_threshold', 'warning',
     '{"component":"co2:0","field":"co2","operator":"gt","threshold":1000}'::jsonb, 300, 1800,
     'High CO2 at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported CO2 above 1000 ppm.',
     TRUE),

    ('builtin:tvoc_above_500', 'Air Quality',
     'TVOC above 500',
     'Fires when a TVOC sensor reads above 500.',
     'component_threshold', 'warning',
     '{"component":"tvoc:0","field":"tvoc","operator":"gt","threshold":500}'::jsonb, 300, 1800,
     'High TVOC at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported TVOC above 500.',
     TRUE),

    ('builtin:power_above_2kw', 'Energy',
     'Power above 2 kW',
     'Fires when an energy meter reads total active power above 2 kW.',
     'component_threshold', 'warning',
     '{"component":"em:0","field":"total_act_power","operator":"gt","threshold":2000}'::jsonb, 60, 600,
     'High power draw on {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported active power above 2000 W.',
     TRUE),

    ('builtin:switch_power_above_1kw', 'Energy',
     'Switch power above 1 kW',
     'Fires when a relay/plug channel reports active power above 1 kW.',
     'component_threshold', 'warning',
     '{"component":"switch:0","field":"apower","operator":"gt","threshold":1000}'::jsonb, 60, 600,
     'High switch power on {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported switch power above 1000 W.',
     TRUE),

    ('builtin:voltage_above_250', 'Energy',
     'Voltage above 250 V',
     'Fires when mains voltage rises above 250 V.',
     'component_threshold', 'warning',
     '{"component":"em1:0","field":"voltage","operator":"gt","threshold":250}'::jsonb, 60, 600,
     'Overvoltage at {{device.name}}',
     '{{device.name}} ({{device.shellyID}}) reported voltage above 250 V.',
     TRUE),

    ('builtin:consumption_above_5kwh_1h', 'Energy',
     'Consumption above 5 kWh in 1 hour',
     'Fires when persisted energy history shows more than 5 kWh consumed in the last hour.',
     'energy_consumption_threshold', 'warning',
     '{"windowSec":3600,"operator":"gt","thresholdKWh":5}'::jsonb, 900, 1800,
     'High hourly consumption at {{device.name}}',
     '{{device.name}} consumed more than 5 kWh in the last hour.',
     TRUE),

    ('builtin:consumption_above_20kwh_24h', 'Energy',
     'Consumption above 20 kWh in 24 hours',
     'Fires when persisted energy history shows more than 20 kWh consumed in the last 24 hours.',
     'energy_consumption_threshold', 'warning',
     '{"windowSec":86400,"operator":"gt","thresholdKWh":20}'::jsonb, 3600, 7200,
     'High daily consumption at {{device.name}}',
     '{{device.name}} consumed more than 20 kWh in the last 24 hours.',
     TRUE),

    ('builtin:relay_on', 'State',
     'Relay turned on',
     'Fires when a switch output turns on. Adjust the component for the channel.',
     'component_state', 'info',
     '{"component":"switch:0","field":"output","equals":true}'::jsonb, 0, 0,
     '{{device.name}} relay on',
     'Relay {{component}} on {{device.name}} is in the ON state.',
     TRUE),

    ('builtin:relay_off', 'State',
     'Relay turned off',
     'Fires when a switch output turns off.',
     'component_state', 'info',
     '{"component":"switch:0","field":"output","equals":false}'::jsonb, 0, 0,
     '{{device.name}} relay off',
     'Relay {{component}} on {{device.name}} is in the OFF state.',
     TRUE),

    ('builtin:cover_open', 'State',
     'Cover opened',
     'Fires when a cover (blind, garage, skylight) reports open.',
     'component_state', 'warning',
     '{"component":"cover:0","field":"state","equals":"open"}'::jsonb, 0, 0,
     '{{device.name}} cover opened',
     'Cover {{component}} on {{device.name}} reports open.',
     TRUE),

    ('builtin:cover_closed', 'State',
     'Cover closed',
     'Informational notice when a cover reports closed.',
     'component_state', 'info',
     '{"component":"cover:0","field":"state","equals":"closed"}'::jsonb, 0, 0,
     '{{device.name}} cover closed',
     'Cover {{component}} on {{device.name}} reports closed.',
     TRUE),

    ('builtin:door_open', 'State',
     'Door/Window opened',
     'Fires when a promoted BLU door/window sensor reports open.',
     'component_state', 'warning',
     '{"component":"bthomesensor:*","field":"state","equals":"open"}'::jsonb, 30, 60,
     '{{device.name}} opened',
     'Door/window {{device.name}} reports open.',
     TRUE),

    ('builtin:door_open_held_5min', 'State',
     'Door/Window open for 5 minutes',
     'Fires only after a promoted BLU door/window sensor stays open for 5 minutes.',
     'component_state', 'warning',
     '{"component":"bthomesensor:*","field":"state","equals":"open","forSec":300}'::jsonb, 300, 600,
     '{{device.name}} left open',
     'Door/window {{device.name}} has stayed open for 5 minutes.',
     TRUE),

    ('builtin:door_closed', 'State',
     'Door/Window closed',
     'Informational notice when a door/window sensor reports closed.',
     'component_state', 'info',
     '{"component":"bthomesensor:*","field":"state","equals":"closed"}'::jsonb, 30, 60,
     '{{device.name}} closed',
     'Door/window {{device.name}} reports closed.',
     TRUE),

    ('builtin:presence_detected', 'State',
     'Presence detected',
     'Fires when a presence component reports present.',
     'component_state', 'warning',
     '{"component":"presence:*","field":"presence","equals":true}'::jsonb, 60, 300,
     'Presence at {{device.name}}',
     '{{device.name}} reports presence.',
     TRUE),

    ('builtin:occupancy_detected', 'State',
     'Occupancy detected',
     'Fires when an occupancy component reports occupied.',
     'component_state', 'warning',
     '{"component":"occupancy:*","field":"occupancy","equals":true}'::jsonb, 60, 300,
     'Occupancy at {{device.name}}',
     '{{device.name}} reports occupancy.',
     TRUE),

    ('builtin:carbon_monoxide_detected', 'Safety',
     'Carbon monoxide detected',
     'Fires when a BLU carbon monoxide sensor reports alarm.',
     'component_state', 'critical',
     '{"component":"bthomesensor:*","field":"value","equals":true}'::jsonb, 0, 300,
     'CARBON MONOXIDE at {{device.name}}',
     'Carbon monoxide sensor {{device.name}} is in alarm.',
     TRUE),

    ('builtin:gas_detected', 'Safety',
     'Gas detected',
     'Fires when a BLU gas sensor reports alarm.',
     'component_state', 'critical',
     '{"component":"bthomesensor:*","field":"value","equals":true}'::jsonb, 0, 300,
     'GAS alarm at {{device.name}}',
     'Gas sensor {{device.name}} is in alarm.',
     TRUE),

    ('builtin:tamper_detected', 'Safety',
     'Tamper detected',
     'Fires when a tamper component reports active.',
     'component_state', 'warning',
     '{"component":"tamper:*","field":"tamper","equals":true}'::jsonb, 0, 300,
     'Tamper at {{device.name}}',
     '{{device.name}} reports tamper.',
     TRUE),

    ('builtin:vibration_detected', 'Safety',
     'Vibration detected',
     'Fires when a vibration component reports active.',
     'component_state', 'warning',
     '{"component":"vibration:*","field":"vibration","equals":true}'::jsonb, 0, 300,
     'Vibration at {{device.name}}',
     '{{device.name}} reports vibration.',
     TRUE),

    ('builtin:garage_door_open', 'State',
     'Garage door open',
     'Fires when a garage door component reports open.',
     'component_state', 'warning',
     '{"component":"garage_door:*","field":"state","equals":"open"}'::jsonb, 30, 300,
     'Garage door open at {{device.name}}',
     '{{device.name}} reports garage door open.',
     TRUE),

    ('builtin:lock_unlocked', 'State',
     'Lock unlocked',
     'Fires when a lock component reports unlocked.',
     'component_state', 'warning',
     '{"component":"lock:*","field":"state","equals":"unlocked"}'::jsonb, 30, 300,
     'Lock unlocked at {{device.name}}',
     '{{device.name}} reports unlocked.',
     TRUE),

    ('builtin:sound_detected', 'Activity',
     'Sound detected',
     'Fires when a sound component reports active.',
     'component_state', 'warning',
     '{"component":"sound:*","field":"sound","equals":true}'::jsonb, 60, 300,
     'Sound at {{device.name}}',
     '{{device.name}} reports sound.',
     TRUE),

    ('builtin:firmware_failed', 'Operations',
     'Firmware update failed',
     'Fires when a firmware update fails on a device.',
     'firmware_operation_failed', 'warning',
     '{}'::jsonb, 0, 0,
     'Firmware update failed on {{device.name}}',
     'A firmware operation on {{device.name}} ({{device.shellyID}}) failed.',
     FALSE),

    ('builtin:backup_failed', 'Operations',
     'Backup failed',
     'Fires when a device configuration backup fails.',
     'backup_operation_failed', 'warning',
     '{}'::jsonb, 0, 0,
     'Backup failed for {{device.name}}',
     'A configuration backup for {{device.name}} ({{device.shellyID}}) failed.',
     FALSE),

    ('builtin:automation_failed', 'Operations',
     'Automation run failed',
     'Fires when a scheduled automation run fails.',
     'automation_run_failed', 'warning',
     '{}'::jsonb, 0, 0,
     'Automation failed: {{device.name}}',
     'An automation run on {{device.name}} ({{device.shellyID}}) failed.',
     FALSE)
ON CONFLICT (COALESCE(organization_id, ''), template_key) DO NOTHING;

--------------DOWN
DELETE FROM notifications.alert_rule_templates
WHERE organization_id IS NULL
  AND template_key LIKE 'builtin:%';

-- Restore the legacy built-in seeds (6303 + 20012) so rollback is clean.
INSERT INTO notifications.alert_rule_templates (
    template_key, category, label, description,
    kind, severity, config, dedupe_window_sec, cooldown_sec,
    summary_template, message_template, auto_resolve
) VALUES
    ('device-offline-critical', 'device-health', 'Device offline (critical)',
     'Fire when the device has been offline for 5 minutes or more.',
     'device_offline', 'critical', '{"offlineForSec":300}'::jsonb, 60, 0, NULL, NULL, TRUE),
    ('device-back-online', 'device-health', 'Device back online',
     'Informational notice when a previously-offline device reconnects.',
     'device_back_online', 'info', '{}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('battery-low-warning', 'battery', 'Battery low (warning)',
     'Warn when battery drops below 20%.',
     'battery_below', 'warning', '{"thresholdPct":20}'::jsonb, 3600, 0, NULL, NULL, TRUE),
    ('battery-critical', 'battery', 'Battery critical',
     'Escalate when battery drops below 10%.',
     'battery_below', 'critical', '{"thresholdPct":10}'::jsonb, 3600, 0, NULL, NULL, TRUE),
    ('smoke-alarm', 'safety', 'Smoke alarm',
     'Critical alert whenever a smoke sensor reports alarm.',
     'smoke_alarm', 'critical', '{}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('flood-alarm', 'safety', 'Flood alarm',
     'Critical alert whenever a flood sensor reports alarm.',
     'flood_alarm', 'critical', '{}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('motion-detected', 'motion', 'Motion detected',
     'Informational notice on motion events with a 5-minute auto-clear.',
     'motion_detected', 'info', '{"clearTimeoutSec":300}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('firmware-update-failed', 'operations', 'Firmware update failed',
     'Warn when a firmware job completes with an error.',
     'firmware_operation_failed', 'warning', '{}'::jsonb, 0, 0, NULL, NULL, FALSE),
    ('backup-failed', 'operations', 'Backup failed',
     'Warn when a scheduled backup run fails.',
     'backup_operation_failed', 'warning', '{}'::jsonb, 0, 0, NULL, NULL, FALSE),
    ('automation-run-failed', 'operations', 'Automation run failed',
     'Warn when an automation execution fails.',
     'automation_run_failed', 'warning', '{}'::jsonb, 0, 0, NULL, NULL, FALSE),
    ('relay-turned-on', 'state', 'Relay turned on',
     'Notify when a switch output turns on.',
     'entity_state', 'info',
     '{"component":"switch:0","field":"output","equals":true}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('relay-turned-off', 'state', 'Relay turned off',
     'Notify when a switch output turns off.',
     'entity_state', 'info',
     '{"component":"switch:0","field":"output","equals":false}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('cover-opened', 'state', 'Door/Cover opened',
     'Notify when a cover reports open.',
     'entity_state', 'warning',
     '{"component":"cover:0","field":"state","equals":"open"}'::jsonb, 0, 0, NULL, NULL, TRUE),
    ('cover-closed', 'state', 'Door/Cover closed',
     'Informational notice when a cover reports closed.',
     'entity_state', 'info',
     '{"component":"cover:0","field":"state","equals":"closed"}'::jsonb, 0, 0, NULL, NULL, TRUE)
ON CONFLICT (COALESCE(organization_id, ''), template_key) DO NOTHING;
