# shellcheck shell=bash
cmd_help() {
    echo ""
    echo "${BOLD}Fleet Management${RESET} v${FM_SCRIPT_VERSION}"
    echo ""
    echo "${BOLD}Usage:${RESET} ./deploy/deploy-public.sh <command>"
    echo ""
    echo "${BOLD}Commands:${RESET}"
    echo "  ${CYAN}up${RESET}                               Start Fleet Management (idempotent: bootstrap or restart)"
    echo "  ${CYAN}up --mdns${RESET}                        Start with mDNS device discovery"
    echo "  ${CYAN}up --logging${RESET}                     Start with Dozzle log viewer (port ${DOZZLE_PORT:-9999})"
    echo "  ${CYAN}up --env dev${RESET}                     Local dev mode (admin/admin, no Zitadel/SSL, ~60s)"
    echo "  ${CYAN}up --env local${RESET}                   Full local Docker stack with Zitadel"
    echo "  ${CYAN}up --env cloud-test${RESET}              CI cloud-test public-path stack"
    echo "  ${CYAN}up --ssl --domain fm.example.com${RESET} Start with HTTPS (Let's Encrypt)"
    echo "  ${CYAN}up --ssl selfsigned${RESET}              Start with HTTPS (self-signed cert)"
    echo "  ${CYAN}up --ssl custom --domain fm.example.com --cert /path/fullchain.pem --key /path/privkey.pem${RESET}"
    echo "                                     Start with HTTPS (custom certificate)"
    echo "  ${CYAN}upgrade${RESET}                          Pull newer images, then restart (same as: pull + up)"
    echo "  ${CYAN}upgrade --migrate-first --yes${RESET}     Run required DB/Zitadel migration before image upgrade"
    echo "  ${CYAN}upgrade --soak <sec>${RESET}             Extend post-health soak window; auto-rolls back on degradation"
    echo "  ${CYAN}migrate --plan-only${RESET}              Print DB/Zitadel/FM migration plan + inventory/report paths"
    echo "  ${CYAN}migrate --yes${RESET}                    Execute required staged DB/Zitadel/FM migration with rollback"
    echo "  ${CYAN}migrate --verify-restore auto|strict|off${RESET}"
    echo "                                   Control backup restore drills before destructive migration steps"
    echo "  ${CYAN}rollback${RESET}                         Revert FM to fleet-manager:rollback (tagged by previous upgrade)"
    echo "  ${CYAN}down${RESET}                             Stop Fleet Management and keep data"
    echo "  ${CYAN}down --volumes${RESET}                   Stop Fleet Management and delete all data (asks for confirmation)"
    echo "  ${CYAN}down --volumes --yes${RESET}             Same as above, skip confirmation (for scripting/CI)"
    echo "  ${CYAN}status${RESET}                           Show service status and health"
    echo "  ${CYAN}logs${RESET} [service]                   Show logs (follow mode)"
    echo "  ${CYAN}ip${RESET}                               Show access URLs"
    echo "  ${CYAN}doctor${RESET} [--ssl ...]               Troubleshoot readiness, dependencies, and SSL configuration"
    echo "  ${CYAN}rotate-secrets${RESET} [--all]           Rotate JWT, FM encryption key, and/or postgres password"
    echo "  ${CYAN}backup-state${RESET} (--age-recipient FILE|--passphrase)"
    echo "                                   Encrypted tarball of deploy/state/ (creds, keys, certs)"
    echo "  ${CYAN}backup-db${RESET} <list|inspect|verify|create|restore>"
    echo "                                   Fleet DB backups with manifests and checksum verification"
    echo "  ${CYAN}upgrade-audit${RESET} <snapshot|snapshot-zitadel|compare|zitadel-plan>"
    echo "                                   Pre/post migration snapshots and Zitadel staged-upgrade plan"
    echo "  ${CYAN}seed${RESET} [--reset]                   Populate demo data (countries, buildings, groups, tags, persona)"
    echo "  ${CYAN}help${RESET}                             Show this help"
    echo ""
    echo "${BOLD}Global Options:${RESET}"
    echo "  ${CYAN}--debug${RESET}                           Print traced shell commands and extra diagnostics"
    echo "                                    Normal mode keeps installers and Docker orchestration quiet unless something fails."
    echo ""
    echo "${BOLD}Public Quick Start:${RESET}"
    echo "  ${CYAN}./deploy/deploy-public.sh up${RESET} is idempotent — bootstraps on first run, restarts on subsequent runs."
    echo "  On Linux this may prompt for sudo during the first run."
    echo "  On macOS it may trigger Homebrew or Docker Desktop permission/setup prompts."
    echo ""
    echo "${BOLD}Which SSL Mode?${RESET}"
    echo "  ${CYAN}selfsigned${RESET}  For anything not publicly issuable by Let's Encrypt:"
    echo "               IPv4 addresses, .local names, split-DNS/internal hostnames, and local domains."
    echo "  ${CYAN}letsencrypt${RESET} For a real public FQDN that resolves publicly to this server and can pass ACME on ports 80/443."
    echo "  ${CYAN}custom${RESET}      For an existing certificate/key pair, including a corporate or internal CA."
    echo ""
    echo "  All SSL modes terminate TLS at Traefik on port 443. --domain accepts a plain hostname,"
    echo "  FQDN, or IPv4 address where supported. host:port and IPv6 literals are not supported."
    echo ""
    echo "${BOLD}Supported platforms:${RESET}"
    echo "  Ubuntu/Debian, Raspberry Pi OS (arm64), Arch Linux, macOS"
    echo ""
    echo "${BOLD}Hardware requirements:${RESET}"
    echo "  Minimum: 4GB RAM, 2 CPU cores, 20GB disk (up to ~50 devices)"
    echo "  Recommended: 8GB RAM, 4 CPU cores, 64GB SSD (up to ~300 devices)"
    echo "  RPi 4B/5 (8GB): works well — use USB SSD instead of SD card for database"
    echo ""
    echo "${BOLD}Storage estimates (300 devices, default retention):${RESET}"
    echo "  Docker images:     ~2GB (one-time)"
    echo "  Device telemetry:  ~500MB (7 day retention, auto-compressed)"
    echo "  Energy meter data: ~5GB/year (1 year retention, auto-compressed)"
    echo "  Audit logs:        ~200MB/year (90 day retention)"
    echo "  Zitadel + auth DB: ~500MB"
    echo "  Total first year:  ~9GB — easily fits on 64GB SSD"
    echo ""
    echo "${BOLD}Configuration:${RESET}"
    echo "  Edit ${CYAN}deploy/env/public.env${RESET} to change memory, retention, and tuning."
    echo "  Key settings: FM_HEAP_SIZE, PG_SHARED_BUFFERS, STATUS_RETENTION, EM_STATS_RETENTION"
  echo "  Performance tuning: FM_MAX_CONCURRENT_INITS, FM_STATUS_QUEUE_MAX (see docs/tuning.md)"
    echo ""
    echo "${BOLD}Environment overrides:${RESET}"
    echo "  FM_VERSION=${FM_VERSION}  FLEET_MANAGER_PORT=${FLEET_MANAGER_PORT}  ZITADEL_EXTERNALPORT=${ZITADEL_EXTERNALPORT}"
    echo ""
}

# ── Main ──────────────────────────────────────────────────────
