import {getLogger} from 'log4js';

export type InternalMetricKind =
    | 'counter'
    | 'gauge'
    | 'labeled_counter'
    | 'labeled_gauge';

// These names intentionally share one labeled Prometheus family per kind.
// Dedicated metric families belong in COUNTER_DEFS or the labeled definitions.
const INTERNAL_COUNTER_NAME_LIST = [
    'alert_read_batch_queue_wait_seconds_total',
    'alert_read_batch_read_seconds_total',
    'alert_read_batch_queries',
    'alert_read_batch_fingerprints',
    'alert_read_batch_errors',
    'alert_delivery_no_active_endpoints',
    'alert_delivery_suppressed_by_cooldown',
    'alert_delivery_suppressed_by_silence',
    'alert_dispatch_failures',
    'alert_escalation_no_active_endpoints',
    'alert_escalation_skipped_by_state',
    'alert_escalation_suppressed_by_silence',
    'alert_event_dropped_unknown_org',
    'alert_fire_suppressed_by_active_window',
    'alert_fire_unchanged_skipped',
    'alert_initial_eval_failed',
    'alert_leak_attribution_failed',
    'alert_offline_no_last_seen',
    'alert_offline_pending_scheduled',
    'alert_org_eval_coalesced',
    'alert_org_eval_failed',
    'alert_org_eval_rule_failed',
    'alert_rule_disabled_after_trigger_once',
    'alert_rules_load_failed',
    'alert_subject_resolve_failed',
    'alert_sweep_evaluated',
    'alert_sweep_evaluation_errors',
    'alert_sweep_org_failures',
    'alert_sweep_ticks',
    'alert_trigger_once_disable_errors',
    'audit_evicted_oldest',
    'audit_log_unarmed_calls',
    'audit_overflow_ack_errors',
    'audit_overflow_drain_errors',
    'audit_overflow_drained',
    'audit_overflow_per_row_fallbacks',
    'audit_overflow_poison',
    'audit_overflow_poison_dropped',
    'audit_overflow_reclaimed',
    'audit_overflow_saturated',
    'audit_overflow_cycle_errors',
    'audit_overflow_spill_errors',
    'audit_overflow_spilled',
    'audit_per_row_fallbacks',
    'audit_retention_sweep_errors',
    'audit_retention_swept',
    'audit_write_dropped',
    'authz_async_sync_fast_path',
    'authz_l1_hits',
    'authz_l1_misses',
    'authz_l2_hits',
    'authz_l2_misses',
    'authz_mark_used_failures',
    'authz_shape_rebuild_failed',
    'baseline_change_points_detected',
    'baseline_rebuild_errors',
    'baseline_residual_days_written',
    'baseline_rows_written',
    'baseline_tick_errors',
    'bthome_telemetry_target_resolve_failed',
    'cert_auto_renew_failures',
    'custom_kind_gauge_refresh_errors',
    'dashboard_grafana_widget_parse_errors',
    'dashboard_legacy_widget_parse_errors',
    'db_stats_collection_overlap_skipped',
    'db_transaction_second_connection',
    'delivery_metrics_refresh_errors',
    'device_anomaly_transitions_total',
    'device_commands_slow',
    'device_commands_total',
    'device_event_attr_undeclared',
    'device_event_backend_bus_malformed',
    'device_event_default_route',
    'device_event_entries',
    'device_event_evicted',
    'device_event_flushes',
    'device_event_flushes_skipped',
    'device_event_unarmed_calls',
    'device_event_untrusted_skipped',
    'device_event_write_dropped',
    'device_event_write_errors',
    'device_group_metadata_cache_hits_total',
    'device_group_metadata_cache_misses_total',
    'device_group_metadata_invalidations_total',
    'device_groups_lookup_error',
    'device_identity_fence_errors_total',
    'device_identity_mismatch_total',
    'device_ingest_append_errors',
    'device_ingest_bypassed',
    'device_ingest_drain_errors',
    'device_inits_cluster_degraded_open',
    'device_inits_cluster_rejected',
    'device_inits_queue_stale_dropped',
    'device_inits_slow_success',
    'device_inits_succeeded',
    'device_load_failures',
    'device_load_reconcile_recovered',
    'device_ownership_claim_rejected_total',
    'device_ownership_errors_total',
    'device_ownership_heartbeat_coalesced_total',
    'device_ownership_lost_total',
    'device_post_accept_unhealthy',
    'device_shadow_errors_total',
    'device_trust_cache_errors_total',
    'device_trust_cache_evictions_total',
    'device_trust_cache_hits_total',
    'device_trust_cache_misses_total',
    'em_completeness_check_failed',
    'em_completeness_counter_mismatches',
    'em_completeness_missing_ranges',
    'em_completeness_sweep_errors',
    'em_live_debug_errors',
    'em_live_debug_values_dropped',
    'em_sync_catchup_yielded',
    'em_sync_channel_cap_blocked',
    'em_sync_future_cursors_rejected',
    'em_sync_identity_change_aborts',
    'em_sync_partial_channel_failure',
    'em_sync_device_gap_minutes',
    'em_sync_pull_deferred',
    'em_sync_pull_records',
    'em_sync_record_bad_clock',
    'em_sync_push_batches',
    'em_sync_push_keys_unavailable',
    'em_sync_push_received',
    'em_sync_push_records',
    'em_sync_push_rejected',
    'em_sync_starvation_alerts',
    'em_syncs_channel_failed',
    'em_syncs_seeded_at_boot',
    'em_syncs_skipped_no_data',
    'em_syncs_skipped_offline',
    'energy_domain_contradiction',
    'energy_domain_dc',
    'event_pel_replayed',
    'event_redis_unavailable_fallback',
    'event_replay_cache_bypassed_total',
    'events_path_dispatch_candidates',
    'events_path_dispatch_skipped',
    'events_path_filtered',
    'events_serialized',
    'firmware_scheduler_missed_runs',
    'fm_custom_kind_created',
    'fm_device_kind_invalid_rejected',
    'fm_device_kind_set',
    'fm_scoped_pat_audit_failures',
    'fm_scoped_pat_bulk_revoked',
    'fm_scoped_pat_created',
    'fm_scoped_pat_revoked',
    'fm_scoped_pat_rotated',
    'fm_scoped_pat_used',
    'geo_cache_parse_errors',
    'grafana_alert_webhook_errors',
    'grafana_alert_webhook_rate_limited',
    'grafana_alert_webhook_received',
    'grafana_alert_webhook_rejected',
    'grafana_alert_webhook_unconfigured',
    'grafana_alert_webhook_unknown_org',
    'grafana_proxy_requests',
    'group_flush_enqueue_failures',
    'ingest_pending_counts_failed',
    'ingress_audit_bypassed',
    'ingress_audit_drain_errors',
    'ingress_audit_flush_requeued',
    'ingress_audit_flushed_total',
    'ingress_audit_poison',
    'ingress_audit_postgres_fallback',
    'ingress_audit_push_errors',
    'ingress_audit_unknown_kind',
    'leader_acquire_errors',
    'leader_renew_errors',
    'lifetime_resets_total',
    'mcp_event_journal_batch_retried',
    'mcp_event_journal_capture_shed',
    'mcp_event_journal_debug_refresh_errors',
    'mcp_event_journal_device_capture_dropped',
    'mcp_event_journal_prune_errors',
    'mcp_event_journal_resource_capture_dropped',
    'mcp_session_limit_reached',
    'node_red_proxy_requests',
    'notification_inhibition_suppressed',
    'notification_receipt_signature_rejects',
    'organization_access_invalidations_total',
    'outbox_jobs_reclaimed',
    'outbox_motion_clear_cancel_errors',
    'outbox_offline_fire_cancel_errors',
    'outbox_reclaim_sweep_errors',
    'outbox_record_attempt_errors',
    'outbox_record_attempt_retries',
    'outbox_record_attempt_retries_recovered',
    'outbox_record_reconcile_enqueue_errors',
    'outbox_record_reconcile_recovered',
    'outbox_repeat_sweep_errors',
    'outbox_secret_decrypt_errors',
    'outbox_state_hold_cancel_errors',
    'outbox_unflushed_groups_reflushed',
    'outbox_unflushed_sweep_errors',
    'pat_rotate_audit_failures',
    'pat_rotate_compensate_attempts',
    'pat_rotate_compensate_failures',
    'pg_pool_idle_errors',
    'pg_query_statement_timeout_total',
    'plugin_command_queue_full',
    'plugin_command_timeouts',
    'plugin_init_failures_total',
    'plugin_worker_limit_rejections',
    'postgres_tx_commit_hook_failed',
    'rate_limit_redis_errors_total',
    'redis_cmd_errors_total',
    'redis_sub_errors_total',
    'request_dispose_failures',
    'request_dispose_timeouts',
    'reservation_redis_errors_total',
    'sensor_capture_stream_quarantined',
    'sensor_events_append_failed',
    'sensor_numeric_append_failed',
    'session_pending_filter_consumed',
    'session_pending_filter_expired',
    'session_pending_filter_sweep_dropped',
    'session_snapshot_stale_skipped',
    'shelly_connect_emitted',
    'shelly_connect_without_owner',
    'shelly_disconnect_emitted',
    'shelly_legacy_ip_handshake_limited',
    'status_overflow_saturated',
    'status_overflow_ack_errors',
    'status_overflow_cycle_errors',
    'status_overflow_drain_errors',
    'status_overflow_drained',
    'status_overflow_poison',
    'status_overflow_poison_dropped',
    'status_overflow_reclaimed',
    'status_overflow_spill_errors',
    'status_overflow_spilled',
    'status_queue_drops',
    'status_queue_spilled',
    'tariff_pull_errors',
    'tariff_pull_points_stored',
    'tariff_pull_skipped_overlap',
    'unknown_device_event',
    'unknown_device_event_malformed',
    'virtual_counter_rows_captured',
    'virtual_operational_rows_captured',
    'virtual_projection_drain_errors',
    'virtual_projection_rows',
    'virtual_sensor_rows_captured',
    'waiting_room_admit_failed',
    'waiting_room_auto_admit_refused',
    'waiting_room_config_errors',
    'waiting_room_config_timeouts',
    'waiting_room_enrichment_missed',
    'waiting_room_evict_close_errors',
    'waiting_room_gather_dropped',
    'waiting_room_group_add_failed',
    'waiting_room_probe_dropped',
    'ws_resume_gap_broken',
    'ws_resume_grace_expired',
    'ws_resume_takeover',
    'ws_send_dropped_closed',
    'alert_dispatch_abort_failures',
    'device_accept_fresh_probe',
    'device_accept_gather_reused',
    'device_ingress_seen_data_dropped',
    'device_ingress_seen_flush_errors',
    'device_ingress_seen_flushes',
    'device_ingress_seen_flushes_skipped',
    'device_ingress_seen_rows_retried',
    'discovery_mdns_host_rejected',
    'em_stats_data_dropped',
    'energy_classifier_parity_both_null',
    'energy_classifier_parity_legacy_only',
    'energy_classifier_parity_match',
    'energy_classifier_parity_mismatch',
    'energy_classifier_parity_v2_only',
    'firmware_model_mismatch',
    'group_flush_abort_failures',
    'lifetime_data_dropped',
    'lifetime_flush_errors',
    'lifetime_flushes',
    'lifetime_flushes_skipped',
    'notification_receipt_bounced',
    'notification_receipt_complained',
    'notification_receipt_delivered',
    'notification_receipt_suppressed',
    'notification_receipt_unknown',
    'virtual_sensor_rejected_not_value_leaf',
    'virtual_sensor_rejected_not_virtual_number',
    'virtual_sensor_rejected_unknown_role',
    'virtual_sensor_rejected_unknown_unit',
    'virtual_sensor_rejected_writable',
    'waiting_room_quarantined'
] as const;
export type InternalCounterName = (typeof INTERNAL_COUNTER_NAME_LIST)[number];
export const INTERNAL_COUNTER_NAMES: ReadonlySet<string> = new Set(
    INTERNAL_COUNTER_NAME_LIST
);

const INTERNAL_GAUGE_NAME_LIST = [
    'alert_read_batch_queued',
    'alert_read_batch_oldest_queued_seconds',
    'alert_read_batch_last_size',
    'alert_read_batch_last_queue_wait_seconds',
    'alert_read_batch_last_read_seconds',
    'alert_sweep_db_calls',
    'alert_sweep_duration_seconds',
    'alert_sweep_pace_wait_seconds',
    'alert_sweep_rows_read',
    'alert_sweep_units',
    'baseline_tick_duration_seconds',
    'cert_seconds_to_expiry',
    'db_runtime_postgres_major',
    'db_runtime_status',
    'db_runtime_timescale_match',
    'db_size_bytes',
    'device_init_slot_oldest_held_ms',
    'device_init_slot_oldest_queued_ms',
    'device_init_slots_active',
    'device_init_slots_queued',
    'device_load_gap',
    'device_load_registered',
    'device_load_rows',
    'device_ownership_heartbeat_devices',
    'device_ownership_heartbeat_duration_ms',
    'device_ownership_heartbeat_in_progress',
    'device_ownership_leases',
    'devices_total',
    'em_sync_catchup_buffer_paused',
    'em_sync_due_live',
    'em_sync_lagged_channels',
    'em_sync_last_pass_blocks',
    'em_sync_last_pass_ms',
    'em_sync_last_rpc_fetch_ms',
    'em_sync_last_rpc_records',
    'em_sync_pull_pages_waiting',
    'em_sync_pull_writes_waiting',
    'em_sync_required_live_entries_per_second',
    'em_sync_worst_channel_lag_seconds',
    'schema_migrations_applied',
    'session_pending_filter_restore',
    'session_snapshot_restored_sessions',
    'token_seconds_to_expiry',
    'wal_bytes_total',
    'wal_fpi_total',
    'wal_records_total',
    'ws_max_buffered_kb',
    'ws_resume_parked_sessions',
    'custom_kind_in_use',
    'em_sync_oldest_held_ms',
    'em_sync_stuck'
] as const;
export type InternalGaugeName = (typeof INTERNAL_GAUGE_NAME_LIST)[number];
export const INTERNAL_GAUGE_NAMES: ReadonlySet<string> = new Set(
    INTERNAL_GAUGE_NAME_LIST
);

const INTERNAL_LABELED_COUNTER_NAME_LIST = [
    'alert_fire_failed',
    'background_signal_failed_total',
    'best_effort_failed_total',
    'carbon_electricitymaps_calls_total',
    'delivery_rate_limited_total',
    'device_commands_failed_total',
    'device_commands_unsupported_total',
    'device_gather_abandoned_total',
    'device_ingest_appended_total',
    'device_ingest_drained_total',
    'device_ingest_poison_dropped_total',
    'device_ingest_reclaimed_total',
    'device_init_slot_reclaimed_total',
    'event_delivered_bytes',
    'event_filtered_total',
    'event_inmem_send_dropped_slow',
    'event_inmem_send_total',
    'event_resync_required',
    'event_xack_total',
    'event_xadd_total',
    'fm_report_section_rendered',
    'fm_report_template_created',
    'fm_report_template_run',
    'formatter_fallback',
    'formatter_invoked',
    'geo_cache_hits_total',
    'geo_nominatim_calls_total',
    'geo_search_total',
    'leader_acquired_total',
    'leader_lost_total',
    'pubsub_handler_errors_total',
    'pubsub_poison_total',
    'pubsub_published_total',
    'pubsub_received_total',
    'redis_group_recreated_total',
    'rollup_eval_null',
    'rollup_path_unresolved',
    'singleflight_dedup_hits',
    'waiting_room_probe_failures',
    'widget_contract_subscriptions'
] as const;
export type InternalLabeledCounterName =
    (typeof INTERNAL_LABELED_COUNTER_NAME_LIST)[number];
export const INTERNAL_LABELED_COUNTER_NAMES: ReadonlySet<string> = new Set(
    INTERNAL_LABELED_COUNTER_NAME_LIST
);

const INTERNAL_LABELED_GAUGE_NAME_LIST = [
    'alert_rule_evaluation_wait_seconds'
] as const;
export type InternalLabeledGaugeName =
    (typeof INTERNAL_LABELED_GAUGE_NAME_LIST)[number];
export const INTERNAL_LABELED_GAUGE_NAMES: ReadonlySet<string> = new Set(
    INTERNAL_LABELED_GAUGE_NAME_LIST
);

const logger = getLogger('observability');
const reportedUnregisteredMetrics = new Set<string>();
const MAX_REPORTED_UNREGISTERED_METRICS = 100;

export function reportUnregisteredMetric(
    kind: InternalMetricKind,
    name: string
): void {
    const key = `${kind}:${name}`;
    if (reportedUnregisteredMetrics.has(key)) return;
    if (reportedUnregisteredMetrics.size >= MAX_REPORTED_UNREGISTERED_METRICS) {
        return;
    }
    reportedUnregisteredMetrics.add(key);
    logger.error(
        'Rejected unregistered observability metric kind=%s name=%s',
        kind,
        name
    );
}
