{
 "title": "Energy Usage Variants",
 "description": "A dashboard that shows your home energy usage. Using Prometheus, Home Assistant and the Emporia Vue 2.",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "devices",
    "label": "Devices",
    "query": "SELECT\n    id AS __value,\n    CASE WHEN\n        jdoc #>'{info, name}' != 'null'\n    THEN\n        jdoc #>> '{info, name}'\n    ELSE\n        jdoc #>> '{info, id}'\n    END AS __text\nfrom device.list;"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 5 Devices Currently Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(se.external_id) id,\n  SUM(s.sum_val) energy_wh\nFROM device_em.energy_15min s\nLEFT JOIN device.list se ON s.device = se.id\nWHERE\n    1 = 1\n    AND s.device IN($devices)\n    AND s.tag = 'total_act_energy'\n    AND s.bucket BETWEEN now() - '1 hour'::INTERVAL AND NOW()\nGROUP BY\n  s.device\nORDER BY energy_wh DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Current Month Total Power Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    t1.bucket,\n    SUM(t1.diff) energy_wh\nFROM (\n    SELECT\n      s.device,\n      s.bucket::date,\n      SUM(s.sum_val) diff\n    FROM device_em.energy_15min s\n    WHERE\n        1 = 1\n        AND s.device IN($devices)\n        AND s.tag = 'total_act_energy'\n        AND s.bucket BETWEEN date_trunc('month', current_date) AND NOW()\n    GROUP BY\n      s.device,\n      s.bucket::date\n  ) t1\n  GROUP BY\n    t1.bucket"
    }
   ]
  },
  {
   "title": "Current Month Imported Energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    SUM(s.sum_val) / 1000 AS consumption_kwh\nFROM device_em.energy_15min s\nWHERE\n    s.device IN($devices)\n    AND s.tag = 'total_act_energy'\n    AND s.commodity = 'electricity'\n    AND s.electrical_source IS NOT DISTINCT FROM 'ac_mains'\n    AND s.bucket BETWEEN date_trunc('month', current_date) AND NOW()\n"
    }
   ]
  },
  {
   "title": "Current Day Power Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    t1.b bucket,\n    sum(diff) energy_wh\nFROM (\n    SELECT\n      s.device,\n      time_bucket('1 hours', s.bucket) b,\n      SUM(s.sum_val) diff\n    FROM device_em.energy_15min s\n    WHERE\n        1 = 1\n        AND s.device IN($devices)\n        AND s.tag = 'total_act_energy'\n        AND s.bucket BETWEEN now() - '1 day'::INTERVAL AND NOW()\n    GROUP BY\n      s.device,\n      b\n) t1\ngroup by t1.b"
    }
   ]
  },
  {
   "title": "Current Day Imported Energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    SUM(s.sum_val) / 1000 AS consumption_kwh\nFROM device_em.energy_15min s\nWHERE\n    s.device IN($devices)\n    AND s.tag = 'total_act_energy'\n    AND s.commodity = 'electricity'\n    AND s.electrical_source IS NOT DISTINCT FROM 'ac_mains'\n    AND s.bucket BETWEEN now()::date::timestamp AND NOW()"
    }
   ]
  },
  {
   "title": "Month Power Total",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ss.external_id,\n  SUM(s.sum_val) energy_wh\nFROM device_em.energy_15min s\nLEFT JOIN device.list ss ON s.device = ss.id\nWHERE\n    1 = 1\n    AND s.device IN($devices)\n    AND s.tag = 'total_act_energy'\n    AND s.bucket BETWEEN date_trunc('month', now()) AND NOW()\nGROUP BY\n  s.device,\n  ss.external_id"
    }
   ]
  },
  {
   "title": "Hourly Power by Device",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n    s.external_id,\n    $__timeGroupAlias(t1.bucket, '1h'),\n    pw energy_wh\nFROM (\n    WITH main as (\n        SELECT\n            date_trunc('hour', s.bucket) bucket,\n            s.device,\n            SUM(s.sum_val) energy_wh,\n            ROW_NUMBER () OVER (PARTITION BY s.device ORDER BY s.device, date_trunc('hour', s.bucket)) rn\n        FROM device_em.energy_15min s\n        WHERE\n            s.device IN($devices)\n            AND s.tag = 'total_act_energy'\n            AND s.bucket BETWEEN now()::date - interval '24h' AND NOW()\n        GROUP BY\n            s.device,\n            date_trunc('hour', s.bucket)\n        ORDER BY\n            s.device\n    )\n    select\n        t1.*,\n        (t1.energy_wh - CASE WHEN t2.energy_wh IS NULL THEN 0 ELSE t2.energy_wh END) pw\n        FROM main t1\n        LEFT JOIN main t2 ON t2.id = t1.id AND t2.rn = t1.rn - 1\n) t1\nLEFT JOIN device.list s ON s.device = t1.id"
    }
   ]
  },
  {
   "title": "Top 5 Devices Last 7 Days",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MIN(se.external_id) id,\n  SUM(s.sum_val) energy_wh\nFROM device_em.energy_15min s\nLEFT JOIN device.list se ON s.device = se.id\nWHERE\n    1 = 1\n    AND s.device IN($devices)\n    AND s.tag = 'total_act_energy'\n    AND s.bucket BETWEEN now() - '7 days'::INTERVAL AND NOW()\nGROUP BY\n  s.device\nORDER BY energy_wh DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Daily Power Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n    b bucket,\n    SUM(diff) energy_wh\nFROM (\n    SELECT\n        s.device,\n        date_trunc('day', s.bucket) b,\n        SUM(s.sum_val) diff\n    FROM device_em.energy_15min s\n    WHERE\n        1 = 1\n        AND s.device IN($devices)\n        AND s.tag = 'total_act_energy'\n        AND s.bucket BETWEEN date_trunc('day', now()) - INTERVAL '8 days' AND NOW()\n    GROUP BY\n        s.device,\n        b\n    ORDER BY b, s.device\n) x\nGROUP BY b"
    }
   ]
  },
  {
   "title": "Power Spikes This Week",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroupAlias(s.bucket, '1h'),\n    SUM(s.sum_val) energy_wh\nFROM device_em.energy_15min s\nWHERE\n    s.device IN($devices)\n    AND s.tag = 'total_act_energy'\n    AND s.bucket BETWEEN now() - INTERVAL '7 days' AND NOW()\nGROUP BY\n    s.device,\n    \"time\"\nORDER BY \"time\", s.device"
    }
   ]
  },
  {
   "title": "Presence",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT b bucket, presence, se.external_id FROM (\n  SELECT\n      time_bucket_gapfill(INTERVAL '5 min', s.bucket, NOW() - interval '7 days', NOW()) as b,\n      s.id, CASE WHEN MIN(s.field) IS NULL THEN 0 ELSE 1 END presence\n  FROM\n      device.mv__status_presence s\n  WHERE\n      s.id IN($devices)\n      AND $__timeFilter(s.bucket)\n  GROUP BY b, s.id\n  ORDER BY b,s.id\n) s\nLEFT JOIN device.list se ON s.id = se.id;"
    }
   ]
  }
 ]
}